- README.md
Hi there!
First off: Nice theme! I was about to write my own fork of the agnoster-theme. But yours is more sophisticated. So i'll try to push my thoughts in your theme. ;)
oh-my-zsh provides a way for 3rd party stuff: You can place it in `~/.oh-my-zsh/custom`. So you don't need to symlink your theme in the official themes-folder.
> Better installation instructions.

- README.md
- powerlevel9k.zsh-theme
The `themes`-folder will automatically created, when invoking `git clone .../powerlevel9k themes/powerlevel9k`..
> A bit simpler installation instructions.

- README.md
- powerlevel9k.zsh-theme
Added an option to set prompt on a new line.
This is just a port of https://github.com/robbyrussell/oh-my-zsh/pull/2984
> Prompt on newline

- README.md
- powerlevel9k.zsh-theme
By setting `POWERLEVEL9K_COLOR_SCHEME="light"` you can use the theme with a light color scheme.
This is just a loose port of https://github.com/robbyrussell/oh-my-zsh/pull/3690
> Added a "light" color scheme

- README.md
Just mentioned solarized color scheme in the customization instructions..
> Mentioned solarized color scheme in the customization instructions.

- README.md
- powerlevel9k.zsh-theme
Show stashes in prompt.
Just a port from https://github.com/whiteinge/dotfiles/blob/5dfd08d30f7f2749cfc60bc55564c6ea239624d9/.zsh_shouse_prompt#L268
> Show stash count

- README.md
- powerlevel9k.zsh-theme
Just a small improvement this time: Made the time format customizable.
> Better configurability of time format

- README.md
> Fixed indendation

- powerlevel9k.zsh-theme
> Typo corrected.

- powerlevel9k.zsh-theme
Long time no see ;)
On a colleagues machine we had some issues regarding whitespaces. I am not sure what the rootcause is, but trimming the whitespaces does the job.
> Trim unwanted whitespaces.

- powerlevel9k.zsh-theme
Yeah. Nothing special. Just a little hint..
> More debugging hints added.

- README.md
- powerlevel9k.zsh-theme
Till now, there is just the choice of a complete color scheme. By this pull request it is possible to define foreground and background color for each segment separately.
This is a loose port of https://github.com/robbyrussell/oh-my-zsh/pull/3434
> More flexible colorsettings

- README.md
Thanks for getting the antigen support in! On a first try everything seems to work fine btw.
I just saw that the repository in the README example was not correct... I also mentioned (as it took me some time to figure out) that you need to define customizations before calling `antigen theme`.
> updated info for antigen install option

- README.md
- powerlevel9k.zsh-theme
Here we go! This fixes issue #47
> Fix the branch icon and whitespaces in the vcs segment.

- powerlevel9k.zsh-theme
Just a small improvement, but it helps me every time I edit the theme with VIM.
> When opening this file in VIM set "expanded tabs"-option and set encoding to "utf8"

- README.md
- powerlevel9k.zsh-theme
This is just a little developers guide, as the theme grew quite big..
> Add a little developers guide

- README.md
- powerlevel9k.zsh-theme
Added a prompt that displays the node version.
> Added node prompt

- README.md
- powerlevel9k.zsh-theme
Now the multiline-prompt is customizable. I see some folks forking the theme, just to set another multiline prompt icon. With this PR these forks become redundant. :)
> Multiline icons customizable

- powerlevel9k.zsh-theme
Pull request per https://github.com/bhilburn/powerlevel9k/commit/d8ed0964866bb9e187b26a88fd19404f6be39262#commitcomment-12902303. :-)
> Set RETVAL for left prompt also.

- powerlevel9k.zsh-theme
Here is the icon protection. Thanks to @apjanke for the great work!
This fixes #56
> Icon protection

- powerlevel9k.zsh-theme
.. There are still some suggestions unmatched, but these are mostly not possible. I managed to get from 116 comments to 25, which is pretty good. :)
> Made the code comply to shellcheck.net suggestions as much as possible

- README.md
- powerlevel9k.zsh-theme
Just a little cleanup:
- Shellcheck-support for vi_mode segment
- alphabetical order of prompts.
> VI-mode cleanup

- README.md
- powerlevel9k.zsh-theme
Branched off `next` branch as asked #105
> Added awesome fontconfig support

- powerlevel9k.zsh-theme
> Added awesome fontconfig for next icons

- powerlevel9k.zsh-theme
Now VCS_INFO is only invoked if VCS segment is activated.
> Vcs cleanup

- README.md
- powerlevel9k.zsh-theme
Just a little customization for the `vi_mode` segment. This is one step to integrate @mustig s changes.
> vi_mode segement more customizable.

- README.md
- powerlevel9k.zsh-theme
Separated `load` and `ram`. Now ram has its own segment. For me the valuable information about memory is free ram and used swap. The new ram segment is capable of displaying both values.
> Ram prompt

- powerlevel9k.zsh-theme
> added variable to have rprompt on the newline

- powerlevel9k.zsh-theme
This closes issue #151, and also makes the coloring make more sense. Now the color of the text follows the color of the icon, i.e. red text for low battery, yellow for charging, etc.
> Battery segment fix and enhancement.

- powerlevel9k.zsh-theme
Just stumbled upon some code-issues in the `node_version` and `nvm` segments.
> Node cleanup

- CHANGELOG.md
- README.md
- powerlevel9k.zsh-theme
...into a `background_jobs`, `root_indicator` and `status` segment.
This fixes #163
> Split up the `status` segment

- README.md
- functions/icons.zsh
- powerlevel9k.zsh-theme
Big thanks to @dritter for guidance, @rjorgenson for great explanation.
And @bhilburn for further guidance and encouragement.
See http://i.imgur.com/2Vncypo.png for a presentation of how it looks.
> Add sub folder icon when in home subdirectories

- powerlevel9k.zsh-theme
Added a check for nvm command, was throwing errors on machines that don't have nvm installed.
> added check for nvm command before running

- README.md
- powerlevel9k.zsh-theme
Just clarified the README section about the `dir` segment and added the visual identifier concept to the `icons_test` segment.
> Minor improvements

- README.md
Also updated [Wiki](https://github.com/Kayant/powerlevel9k/wiki/Install-Instructions).
Tested all frameworks on a clean system.
> Add more ZSH framework instructions

- functions/utilities.zsh
- powerlevel9k.zsh-theme
This PR fixes the joining of conditional segments (#186). It works even with multiple conditional segments.
> Join conditional segments

- CHANGELOG.md
- README.md
- functions/icons.zsh
- powerlevel9k.zsh-theme
> Reworked the AWS-Beanstalk segment

- functions/utilities.zsh
My Fix for #186 was incomplete. Now it works correctly.
> Fix joining segments

- functions/vcs.zsh
Signed-off-by: Sebastien Varrette <Sebastien.Varrette@uni.lu>
In relation with #210
> dirty check even in subdirs

- README.md
- powerlevel9k.zsh-theme
Added function for [nodeenv](https://github.com/ekalinin/nodeenv) in prompt.
P.S. I looked into some previous closed PRs and assumed that `next` is the branch for the next release hence opening PR to `next`.
> Nodeenv support

- README.md
- functions/icons.zsh
- powerlevel9k.zsh-theme
Here is my screenshot for rust icon
> rust icon added

- functions/icons.zsh
Other pull request to set the snake icon for python.
> Changed python icon to snake

- powerlevel9k.zsh-theme
In BSD environment, the load and ram indicator cannot work properly since the current version of theme use Linux command to get related information. 
I add some BSD specified command to collect information from BSD.
> Fix load and ram indicator support for BSD

- powerlevel9k.zsh-theme
With some spelling corrections in `powerlevel9k.zsh-theme` instructional sections as I was trying to figure some things out on how to customize
> helping out

- README.md
- powerlevel9k.zsh-theme
implemented virtualization detection with systemd.
> Detect virt next

- functions/icons.zsh
- functions/vcs.zsh
Hi,
as talked in #359, here is what I have done. Feel free guys to refactor the code, unfortunately my bash skill were not enough :( to extract code into a function and use it in: `+vi-vcs-detect-changes()` later on.
Cheers,
David
> Icon by repo

- powerlevel9k.zsh-theme
The case statement was causing it to never display that it was charging
and some of the awk statements had an off-by-one bug to grab the correct
values.
> Fix MacOS specific battery segment logic.

- CHANGELOG.md
- README.md
- functions/icons.zsh
- powerlevel9k.zsh-theme
This is the first (and easier) segment of @BenoitAverty .
I just renamed it from `dir_permissions` to `dir_writable` and added some documentation.
> Benoits dir writable segment

- README.md
- powerlevel9k.zsh-theme
* refactorized the sourcecode
* added true/false switch
> added ssh support and POWERLEVEL9K_HIDE_HOST feature

- debug/font-issues.zsh
This adds a quite basic font "debugger". Well. It is a script that checks the installed font and outputs a warning message if the font does not contain "nerd", "awesome" or "powerline" in its name..
Btw. I am planning to add more debugging scripts. ;)
> Add font debugger

- CHANGELOG.md
- README.md
- TESTS.md
- functions/icons.zsh
- powerlevel9k.zsh-theme
- test-bsd-vm/Vagrantfile
- test-bsd-vm/bootstrap-zero.sh
- test-bsd-vm/bootstrap.sh
- test-vm-providers/plain.sh
- test-vm/plain.sh
- test/segments/dir.spec
- test/segments/vcs.spec
For now here are the changes:
* For OS X display the sum of Pages free and Pages inactive. See https://support.apple.com/en-us/HT201538
* For Non BSD use MemAvailable instead of MemFree. See http://www.linuxatemyram.com/
For now no satisfying solution has been found for BSD systems
> Improves ram prompt #415

- CHANGELOG.md
- debug/iterm.zsh
This PR adds some entries to the CHANGELOG 😒 
Aaand *drumroll* a debugging script for iTerm2. It should find the most common configuration mistakes. 😏
> Add iterm debugger

- .travis.yml
- test-bsd-vm/bootstrap.sh
- test-vm-providers/plain.sh
- test-vm-providers/setup-environment.sh
- test-vm/antigen.sh
- test-vm/bootstrap.sh
- test-vm/omz.sh
- test-vm/prezto.sh
This PR fixes some minor troubles with the BSD VM and sets up some nice test-repos (git, mercurial and subversion) and a deep test folder.
> Improve travis and VMs

- functions/icons.zsh
Will update Wiki once this gets merged.
> Changing name of nerdfont option per #458

- powerlevel9k.zsh-theme
> Make sure prompt_cr is set

- powerlevel9k.zsh-theme
black on yellow was pain for the eyes
> swapped colors for virtualization detection

- functions/icons.zsh
- powerlevel9k.zsh-theme
- test/segments/go_version.spec
The Gopher icon is provided by nerd-font.
> Add Gopher icon to go_version segment

- README.md
- functions/icons.zsh
- powerlevel9k.zsh-theme
move from master to next branch
> add vpn ip to prompt

- powerlevel9k.zsh-theme
> rvm: handle -head, etc. more gracefully.

- functions/icons.zsh
> Update OK_ICON weight to match FAIL_ICON

- README.md
- powerlevel9k.zsh-theme
- test/segments/dir.spec
> Add TRUNCATE_TO_UNIQUE shortening dir strategy

- README.md
- powerlevel9k.zsh-theme
This commit adds a functionality to choose if one wants to see 1, 5 or
15 minutes average.
Resolves issue #604
> Add average choice to load extension

- functions/icons.zsh
Simple correction (see comment)
> Corrected awesome-fontconfig lock icon

- .gitignore
- README.md
Add documentation for VCS hooks config
> Add documentation for VCS hooks config

- README.md
As per the discussion at #646.
> remove weird glyphs in README.md

- README.md
- powerlevel9k.zsh-theme
Allow showing the number of jobs even if there is <= 1 job present.
Solves #561 better.
> Allow showing the number of jobs even if there is <= 1 job present.

- powerlevel9k.zsh-theme
> pyenv promt segment uses $PYENV_VERSION environment variable"

- README.md
- powerlevel9k.zsh-theme
> OpenFOAM support! (fixes #696)

- README.md
- functions/icons.zsh
- powerlevel9k.zsh-theme
Added `prompt_date` (seems to have been skipped somehow)
Fixed up segment comments by adding separators (#####) and descriptions where required
Added `TIME_ICON` (also seems to have been omitted)
> Added `prompt_date` and fixed segment comments

- README.md
- functions/utilities.zsh
- powerlevel9k.zsh-theme
- test/powerlevel9k.spec
- test/segments/dir.spec
I have taken @dritter 's latest code from `async_all_the_segments` and merged it with the current code in `next` to create a starting point for working on updating this segment. He has already done some optimizations to speed up the code.
> PROMPT_DIR segment updates

- README.md
The markdown table seems to be broken. This PR fixes that.
> Fix Brightness Table

- powerlevel9k.zsh-theme
- test/powerlevel9k.spec
This fixes #841 
Thanks @billimek for this finding. Could you double check that this fixes your issue?
> Fix RPROMPT placement

- README.md
Explains the states of the `context` segment in the README. Related to #898
> Add new states to context segment in README

- README.md
Add etc icon variable in the dir segment docs
#926 
I didn't found a coherent image for the gear character. Whre does the three other images comes from?
> [Docs] Add etc state description in dir docs

- segments/background_jobs.p9k
- test/segments/background_jobs.spec
Set `BACKGROUND_JOBS` colors background "yellow" and foreground "black" for improved visibility.
> Update `BACKGROUND_JOBS` colors

- functions/utilities.zsh
- segments/vcs.p9k
This PR removes VCS externals grap & tail
> Remove VCS externals

- .travis.yml
This enables tests on ZSH 5.6.1 and 5.6.2
> Test newest zsh versions

- segments/vcs.p9k
This cuts down the use of externals to a minimum. Probably the main issue with speed is the amount of calls to git and huge repositories. I tried to reduce the calls here, but do not expect it to solve issues like #732 ..
> Speedup vcs

- segments/vcs.p9k
These are two small improvements:
1. Use the unaliased git in all cases
2. Avoid using subshells if possible
> Speedup vcs 3

- functions/vcs.zsh
This PR brings the fixes from #1049 to master.
> Speedup vcs master2

- functions/vcs.zsh
- test/segments/vcs-git.spec
This PR is a backport of #1058 onto master.
> Speedup vcs4 master

- segments/dir.p9k
- test/segments/dir.spec
> Make all truncation stratiegies respect P9K_DIR_PATH_ABSOLUTE

- powerlevel9k.zsh-theme
This fixes #968 
@Sasszem could you try this branch, and confirm that it works?
> Make truncate with package name work without setting shorten length

- powerlevel9k.zsh-theme
This fixes #701 
Hey @magicalraccoon and @swatalla could you give this branch a shot?
> Fix vpn_ip segment

- test/segments/vcs_git.spec
- test/segments/vcs_hg.spec
This PR adds vulnerability tests similar to the ones from https://github.com/njhartwell/pw3nage
I added them in a separate pull request, instead of directly in #1027 because this is independent of the implementation to fix #812 (which #1027 is one of).
> Add tests for branch name vulnerability

- test/segments/vcs-git.spec
- test/segments/vcs-hg.spec
> Add vcs vulnerability tests master

- functions/icons.zsh
- test/functions/icons.spec
> Protect locale

- debug/font-issues.zsh
This fixes some issues with the font-debugging script and adapts the newest changes from neofetch.
> Fix font debug

- segments/kubecontext.p9k
- test/segments/kubecontext.spec
Kubernetes general colors are white and blue, so I suggest updating the default background color to blue instead of magenta
Thank you so much for opening a PR for P9k! Many of our best features and segments have come from the community, and we are excited to see your contribution.
To help you make the best PR, here are some guidelines:
- The `master` branch is our *stable* branch, and the `next` branch is our development branch. If you are submitting a bug fix, please file your PR against `master`. If it is a new feature, enhancement, segment, or something similar, please submit it against `next`. For more information, please see our [Developer's Guide](https://github.com/bhilburn/powerlevel9k/wiki/Developer's-Guide).
- We maintain unit tests for segments and features in the `test` …
> [Enhancement] Update kubecontext background color to blue

- .travis.yml
> Test P9K in ZSH 5.7

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/PERFORMANCE_ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
This adds a new Issue Template specifically for Performance Issues.
> Add Performance Issue Template

- CHANGELOG.md
Yep. Add a Changelog. This is the final PR for `v0.6.7`.
// cc @sambadevi
> Add changelog for v0.6.7

- segments/virtualenv/virtualenv.p9k
Correct variable name in virtualenv segment. One-liner.
Fixes #1211 
None
> [Bugfix] virtualenv correct variable name

- segments/disk_usage/disk_usage.spec
- segments/vcs/README.md
- segments/vcs/vcs.p9k
- segments/vcs/vcs_git.spec
- segments/vcs/vcs_hg.spec
- segments/vcs/vcs_svn.spec
This fixes #1202. At least on `next`. The original Issue aims at `master`.
> Fix vcs percent leaks

- segments/dir/dir.p9k
- segments/dir/dir.spec
This fixes #1206 . At least on `next` branch. The original Issue aims at `master`.
Caveat: There are probably more bugs in the dir segment. That segment needs a major refactoring.
> Fix dir issues

- generator/default.p9k
- segments/status/status.spec
- segments/vi_mode/vi_mode.p9k
> [Bugfix] fixes vi_mode update

- segments/anaconda/README.md
This is a forgotten commit when I moved the segments into own folders and merged the wiki infos into the readmes.
> Improve readme of anaconda segment

- segments/dir/dir.p9k
- segments/dir/dir.spec
> [Bugfix] removes need setting P9K_DIR_SHORTEN_LENGTH for truncate_to_unique

- generator/default.p9k
- segments/background_jobs/background_jobs.spec
- segments/ssh/ssh.spec
- segments/status/status.spec
On empty segments there is an additional whitespace that was introduced in #1329 . This is the fix.
> Fix whitespace on empty segments

- functions/colors.zsh
- functions/icons.zsh
- functions/utilities.zsh
- segments/anaconda/anaconda.p9k
- segments/context/context.p9k
- segments/date/date.p9k
- segments/dir/dir.p9k
- segments/host/host.p9k
- segments/time/time.p9k
- segments/user/user.p9k
- segments/vagrant/vagrant.p9k
- segments/vcs/vcs.p9k
- segments/vi_mode/vi_mode.p9k
This was originally discovered by @ZeGentzy in #1338 .
Here we now decompose UTF-8 chars that might be set by the user.
@ZeGentzy could you confirm this works for you?
> [Bugfix] Fix decomposing utf8

- README.md
- functions/icons.zsh
- functions/utilities.zsh
- generator/default.p9k
- powerlevel9k.zsh-theme
- segments/status/status.spec
- test/core/bold.spec
- test/core/joining_segments.spec
- test/core/prompt.spec
- test/core/visual_identifier.spec
- test/powerlevel9k.spec
This PR is a backport from P10K and fixes several problems around multi line prompts.
Fixes #1267 , #1291 and #1306 .
Test are not green right now, because I am waiting for #1329 to be merged..
> [Bugfix] Fix completion menu
