Powerlevel9k/powerlevel9k

README.md, powerlevel9k.zsh-theme
For better customization, you can add an array of elements in your zshrc:
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS
These are arrays, where you can set your prompt-segments.
Example:
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir git)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(longstatus history time)
=> Better customization approach

powerlevel9k.zsh-theme
Check for the $RBENV_VERSION environment variable and, if present,  show a prompt with the ruby version being used.
=> Add a prompt for rbenv ruby version

powerlevel9k.zsh-theme
There is a leading whitespace on the left prompt. Seems like it shouldn't be there, so this fixes that.
Maybe this is how you like it though? Personally, it annoys me :)
=> Remove the leading whitespace from the left prompt.

powerlevel9k.zsh-theme
Now this theme also works with mercurial! :)
Only thing is:
I had to implement a very poor dirty check. Unfortunately I didn't find a better one that works with mercurial and git.. Now I just check, whether the main VCS_INFO-prompt contains a '●' or '✚'..
=> Added mercurial support

README.md, powerlevel9k.zsh-theme
... And the next one ;)
I'd like to display the current changeset-ID in the prompt. Because this is IMHO quite controversial I've added a new switch `POWERLEVEL9K_SHOW_CHANGESET`, which must be enabled.
As an extra, `use-simple` is enabled, if we don't show the changeset. This boosts performance, at least when mercurial is used (as the zsh-documentation says, it affects `bzr` and `hg` only).
=> Display Changeset

README.md, powerlevel9k.zsh-theme
Just added a segment to display the current AWS profile. The profile has to be set in the .zshrc: `export AWS_DEFAULT_PROFILE=<aws_profile_name>`.
This is just a merge of the following pull request into this repo: https://github.com/robbyrussell/oh-my-zsh/pull/3228
=> AWS segment added

README.md
Can't stop harassing you.. :D
Here is just a little wording-fix: VCS_INFO is a feature of ZSH itself, not of oh-my-zsh.. ;)
=> Wording: VCS_INFO is a feature of ZSH itself..

powerlevel9k.zsh-theme
Just a little internal change.
I stumbled upon setting variables in my `~/.zshrc` to false to affect nothing. I had to comment them out, to disable a specific setting..
With this change e.g. `POWERLEVEL9K_SHOW_CHANGESET=false` will work (disable). Before that, it didn't.
=> Correct interpretation of boolean variables.

README.md, powerlevel9k.zsh-theme
Here we show a little ratio of test vs real classes.
This is a loose port of https://gist.github.com/sent-hil/4641437 . I rather do symfony2 than ruby at work, so I extracted a little base method to show the actual prompt. Now the code is quite lean.
It may has some performance issues on large projects, but for most cases it will do nice.
Best regards
:)
=> Show a ratio of test classes vs real classes (Ruby and Symfony2)

README.md
Just wanted to add some documentation on how the test-ratio helper function works. This documentation applies for `rspec_stats` and `symfony2_tests`-functions.
=> Test ratio documentation

README.md, powerlevel9k.zsh-theme
Here is a little port of https://github.com/robbyrussell/oh-my-zsh/pull/3365 . It shows the current active mercurial bookmark if any.
Also this patch contains a nice learning: If you want to override a substring of `hook_com[misc]` just set `ret=1` (from http://www.zsh.org/mla/workers/2010/msg00163.html).
=> Mercurial: show bookmark

powerlevel9k.zsh-theme
This fixes @pradyunsg Issue #33 regarding the RPROMPT. I found the fix on http://superuser.com/questions/357107/zsh-right-justify-in-ps1
=> RPROMPT on the first line

powerlevel9k.zsh-theme
When using [last-working-dir](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/last-working-dir) the problem becomes obvious. When first opening the terminal the prompt suggests the project is not dirty. Refreshing the prompt (simply hitting enter) updates the status accordingly. 
I took a stab at fixing the problem, and put an echo statement in [powerlevel9k.zsh-theme#L401](https://github.com/bhilburn/powerlevel9k/blob/558d137bfaf3b64c5e1b6b1091b0c066cb5f5cce/powerlevel9k.zsh-theme#L401), to see if it was getting called. The echo seemed to get compounded (0 calls on first prompt, 1 on second prompt, 2 on third prompt and so forth). It looks like on each invocation, an additional call was being added to the precmd via the hook. This might cause problems for zsh sessions …
=> Correctly set VCS dirty status on first invocation.

test-vm/omz.sh
Here we go! This fixes the `chsh`-error.
There is still one error during the installation of OMZ, but it works anyway:
==> default: sh: 52: /home/vagrant-omz/.zshrc:
==> default: Syntax error: "(" unexpected
Just log in with `vagrant ssh`, and you'll see a nice shell :).
=> Fixed oh-my-zsh test installation.

README.md, powerlevel9k.zsh-theme
A new Segment that shows the Symfony version number, if the current directory is a Symfony2 project (it looks for a file named `app/bootstrap.php.cache`).
=> Added a segment that shows the Symfony2 version number.

README.md, powerlevel9k.zsh-theme
Now the branch icon is configurable. If you want to display it, simply set `POWERLEVEL9K_SHOW_BRANCH_ICON` to `true`.
Defaults to false.
=> Make branch icon configurable

README.md, powerlevel9k.zsh-theme
With this option you can shorten the output of the `dir` segment by specifying 
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
=> Added option to shorten dir path

README.md, powerlevel9k.zsh-theme
This resolves #41 
@bhilburn Sorry, didn't want to steal the issue from you.
=> Made the `context` segment customizable.

powerlevel9k.zsh-theme
`tr` shouldn't be necessary. `wc` output is imho without spaces.. Otherwise we should truncate the string by the means of zsh.
=> minimize dependencies

powerlevel9k.zsh-theme
At first, I havn't installed `coreutils`. It took me a while to figure out that this was the necessary package to install to get this Theme running. Without `tr`, there is no need to install `coreutils`.
This is the second approach to fix #60 .
@natemccurdy Can you verify my fix? 
Thx. :)
=> Strip the whitespace of OSX `wc` with pure zsh. No need to install `coreutils`.

README.md, powerlevel9k.zsh-theme
Some whitespace fixes, a better example for a customized time format and a troubleshooting hint for non 256-color terminals (as addition to https://github.com/bhilburn/powerlevel9k/pull/30)
=> Various improvements

README.md, powerlevel9k.zsh-theme
Some folks want no right prompt, so here is the possibility for that. I think it would be nicer, if it would be disabled by setting an empty array as `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`, but it seems there is no way in zsh to distinguish between an empty array and a not set variable (at least I didn't found one)..
=> Disable rprompt possible

powerlevel9k.zsh-theme
Per my previous comment, whipped up a couple of utility functions to help set defaults for powerlevel9k configurables.
`defined` does what you think it does - except unlike `-n`, it also works if the variable is defined but empty. Very nifty!
`set_default` allows for a shorthand if your variable is a scalar, e.g: `set_default myvar hello` sets `myvar` to "hello" only if it has not been defined previously.
Unfortunately, `typeset` can't set a value for an array. For arrays, do something like `defined array || array=(1 2 3)`.
Also put in some work to get existing variable checks switched over to use `defined` or `set_default` as appropriate. I didn't go into great depth to see if we could do any refactoring, just grabbed the low hanging fruit for this PR. :-)
=> Implement defined, set_default utility functions

powerlevel9k.zsh-theme
When the repository backend is like git-svn or git-hg, there was a conflict with `zstyle` `formats` from `functions/VCS_INFO_formats`. Now it applies the format to all backends starting with `git` or `svn`.
=> Fix format for git-svn

powerlevel9k.zsh-theme
Just set `export TERM=ansi` or `export TERM=xterm` in your `~/.zshrc` and open a new shell to see the effect. ;)
=> Display a warning, if the terminal supports less than 256 colors.

powerlevel9k.zsh-theme
Therefore the home-icon in the awesome-patched mode should define its whitespace, so that in normal mode no extra whitespace is shown.
This fixes #84
=> Whitespaces should belong to the Icon as they form an entity.

README.md, powerlevel9k.zsh-theme
I was inspired by @Illizian blogpost [here](https://www.alexscotton.com/post/a-modular-responsive-zsh-theme-and-some-bonus-unix-commands) and thought that it would be nice to have such segments as well..
The new segments worked for me in OMZ, Antigen, Prezto, plain ZSH (all vagrant) and a native Linux system.
What comes in this pull request as well is that I changed the Icons for Apple and Linux to glyphs from font-awesome.
=> New segments for system stats and current IP

powerlevel9k.zsh-theme
Now a small segment separator is shown, if two subsequent segments have the same background color.
=> Improve same color segments

powerlevel9k.zsh-theme
I have updated some icons' utf8 code to look better. Old icons were not matched to many icons.
=> Updated few icons to use with git.

README.md, powerlevel9k.zsh-theme
Also, the default for the right side is `longstatus`.
=> Make docs reflect difference between status and longstatus

README.md, powerlevel9k.zsh-theme
As discussed in #96, add a `vi-mode` segment to show the current editing mode, `NORMAL` or `INSERT`.
=> Add vi-mode segment

powerlevel9k.zsh-theme
We introduced separators for same-color segments, but we missed them in the `flat` variant. Here they are.
=> Added subsegments in flat-mode.

README.md, powerlevel9k.zsh-theme
There is now no `longstatus`-segment any more. It had the same intent as the `status` segment and the codebase was almost equal. Now users should use `status` only. To get the behavior of the old status segement, users can set POWERLEVEL9K_STATUS_VERBOSE=false.
Also here I unified the use of named color codes to make the subsegment-display work.
=> status vs longstatus cleanup

powerlevel9k.zsh-theme
If this isn't quoted, in can bleed through to stdout in certain circumstances.
This one is pretty weird, haven't dug in to figure out exactly why it is bleeding through. I know that removing "local" fixes it, but quoting the value also seems to fix it.
It also only occurs if I invoke oh-my-zsh from both my zshrc AND zprofile. Super weird. /shrug
=> Quote value of IS_BSD_SED.

README.md, powerlevel9k.zsh-theme
Prints out the Node version that is currently active if it is different than the default version specified by NVM.
=> Add nvm prompt segment

powerlevel9k.zsh-theme
This is the second customization to integration @mustig s changes.
I didn't include documentation about this feature in the README. I think this feature is not so important and better located in the wiki.
=> Made whitespaces between segment separators customizable

powerlevel9k.zsh-theme
- Literal command to be added is highlighted in blue
- Now beginners won't try to add an incorrect command to ~/.zshrc
=> Rephrasing of error message when TERM not 256 color

README.md, powerlevel9k.zsh-theme
Added a new prompt segment that can show you battery status on. Supports both OS X and Linux. On OS X it will display the time remaining until charged or discharged(not provided by the subsystem on Linux as far as I can tell). Will fail gracefully on any system without a battery.
=> added a prompt segment to display battery status on laptops

powerlevel9k.zsh-theme
This PR fixes the `history-substring`-issue as well as the `home` and `end` keys. This works for me with all frameworks _but_ OMZ with `vi-mode` activated. I used the following configuration (in the vagrant, as we need to source the `history-substring-search` widget):
```zsh
source /home/vagrant-omz/.oh-my-zsh/plugins/history-substring-search/history-substring-search.zsh
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
```
Huge thanks to @apjanke.
=> Issue #131: This fixes history-substring-search, home and end keys.

powerlevel9k.zsh-theme
As #119 is still growing, it is time to harvest some of the fruits there. Here is the performance-improvement part. This is not a pure performance improvement as now the gemset will be printed as well.
Thanks to @rjorgenson for the hint.
=> Huge performance improvement if you use `rvm` segment.

functions/icons.zsh, powerlevel9k.zsh-theme
This is to allow users to have their prompt end in the way they want, e.g. if you want your prompt to end with "$", you can set POWERLEVEL9K_PROMPT_END="$".
=> Add icon for end of left prompt.

powerlevel9k.zsh-theme
The `go_version` segment printed just "go", instead of "go1.2.1". Now it works correctly.
=> Fix for the GO version.

CHANGELOG.md, README.md, powerlevel9k.zsh-theme
This segment allows the user to run an arbitrary command and display the result as a segment. Useful to enable users to monitor whatever they want, without having to muck around in powerlevel9k itself.
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context time battery dir vcs virtualenv custom_command)
POWERLEVEL9K_CUSTOM_COMMANDS=("echo signal: \$(nmcli device wifi | grep yes | awk '{print \$8}')" )
POWERLEVEL9K_CUSTOM_COMMAND_BACKGROUNDS=("blue")
POWERLEVEL9K_CUSTOM_COMMAND_FOREGROUNDS=("yellow")
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(aws status load ram)
gives
Instead of defining the command inline (if it is kinda long or unreadable), one can also add a function to the .zshrc like:
zsh_signal(){
local signal=$(nmcli device wifi | grep yes | awk '{print $8}')
local color='%F{yellow}'
[[ $signal -gt …
=> Custom command segment.

powerlevel9k.zsh-theme
For ZSH 5.0.8 `whence -v` tells also the path to the command. In that case we can use that information to get a proper path to the utility functions.
=> Try to fetch the utility function path automatically

CHANGELOG.md, README.md, functions/icons.zsh, functions/vcs.zsh, powerlevel9k.zsh-theme
I didn't forget about @rjorgenson's wish to easily change the color of an icon from #157 . Now I think I have a good piece of code. 
Now there is a concept of a "visual identifier" of a segment. This is much like a logo of a segment. Before this change we printed the icons into the message that is passed to `left_prompt_segment` and a big part of segments just have one icon..
What this code does is quite simple, `left_prompt_segment` take a new parameter that can have its own color (by setting a variable like `POWERLEVEL9K_<segment>_<state>_VISUAL_IDENTIFIER_COLOR` (e.g. `POWERLEVEL9K_BATTERY_DISCONNECTED_VISUAL_IDENTIFIER='red'`).
A quite extensive example:
```zsh
POWERLEVEL9K_DIR_HOME_VISUAL_IDENTIFIER_COLOR='green'
POWERLEVEL9K_DIR_HOME_FOREGROUND='cyan' …
```
=> Battery segment: rework part 2

README.md, powerlevel9k.zsh-theme
In the FISH-Shell directories are shorten like this: `/u/s/plasma` for `/usr/share/plasma`
I added a new flag __truncate_fish_like__ to POWERLEVEL9K_SHORTEN_STRATEGY and basically removed the ".." from truncate_from_right.
=> added fish-like shortening strategy

powerlevel9k.zsh-theme
Now even segments that just have an icon as content print these icons as visual identifiers. Some of these segments have a verbose mode. If this verbose mode is false, some print just the icon (like the battery segment), which didn't work correctly before this change.
This is because the `$1_prompt_segment` methods checked if the segments had content, and only printed in that case. Now the segments are more in charge of they want to print or not.
=> More consistent visual identifiers

functions/vcs.zsh
I had it in `awesome-patched` mode as well, so I just removed the redundant whitespace.
=> Removed whitespace before git tag

powerlevel9k.zsh-theme
The foreground and background instructions are spaceless by default. No need to make them spaceless explicitly.
=> Removed unnecessary spaceless codes

README.md
As requested in #171 here is the documentation for the "home" and "folder" icons.
I tried to write it in a progressive way (like you want to add these icons), although @natemccurdy 's original intend was to turn these icons off, because I find it hard to formulate the other way around.
The other way would be something like:
```
If you use any of `awesome-patched`, `awesome-fontconfig` or `flat` modes, and you don't
want to show the folder or home icon, you can turn it off by...
```
=> Added an explanation for the "home" and "folder" icons.

CHANGELOG.md
D'oh! I missed some changelog entries on some minor BC breaks.. With introducing state to segments, the variables for them changed.
@bhilburn This commit should also be on master.
Code changes from cd5b4d0debac05a74131f06efa918172586865ec and 5a4de1d2742e6e19a1ffb7ea8c418a923599391e
Additionally, I reworked the [Special Segment Colors](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#special-segment-colors) part in the wiki.
=> Missed changelog entries

powerlevel9k.zsh-theme
The changes to the new method of tracking state broke custom settings for the prompt_load segment. Without this fix it needs ```POWERLEVEL9K_LOAD_STATEBACKGROUND``` instead of ```POWERLEVEL9K_LOAD_STATE_BACKGROUND``` as with the previous version.
=> fixing segment call for new state implementation in prompt_load

functions/icons.zsh
The RVM icon appears to be wider than the font allows for a character, this space at the end makes it look less cramped.
=> added space to end of RVM icon

CHANGELOG.md, powerlevel9k.zsh-theme
I think it should be the default behavior, but I've added `POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE` var to disable it :)
=> background_jobs segment : add number of jobs if >1

CHANGELOG.md, README.md, functions/icons.zsh, powerlevel9k.zsh-theme
This is more flexible, and we save a variable.
If users wish to have this as one segment, the can join them together..
=> Split up `ram` segment into `ram` and `swap`.

powerlevel9k.zsh-theme
This PR is to address #190. Not yet documented, as this is an pretty advanced feature, that will be documented in the wiki.
You can now customize which VCS_INFO hooks you want to have by setting `POWERLEVEL9K_VCS_GIT_HOOKS` (by default `(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)`) or `POWERLEVEL9K_VCS_HG_HOOKS` (by default `(vcs-detect-changes)`).
I think this is more for the upcoming 0.4.0 release..
=> VCS-hooks customizable

CHANGELOG.md, functions/vcs.zsh, powerlevel9k.zsh-theme
It is nice to be able to colorize the VCS section of my prompt to be yellow when there are untracked files in the repository directory that haven't been added yet. So the section of the prompt is green when everything is up to date, yellow if there are untracked files, and red when it is truely "dirty" - when there are changes that haven't been committed. Feel free to modify and/or integrate! Thanks
=> add "yellow" state to prompt for git repos

.gitmodules, .travis.yml, TESTS.md, functions/utilities.zsh, powerlevel9k.zsh-theme, test/functions/colors.spec, test/functions/utilities.spec, test/powerlevel9k.spec, test/segments/dir.spec, test/segments/go_version.spec, test/segments/rust_version.spec
This PR adds unit testing to this project. For now, it tests just "joining of segments" and "dynamic coloring of segments", as this is just a proof-of-concept. I we decide this PR is a good idea, then I'll add more tests..
This theme is very flexible. As a result every change needs a lot of testing. At least I tend to forget certain tests, so the theme gets error prone.
Yep. Intentionally. :smile:
I branched off of 9e191d43058d66fd52d1c33a244523600848bd25 (right before e9da3d5146d5cf881249fa229e27b60428516aab), where joining of Segments is broken, so `testJoinedSegments` and `testTransitiveJoinedSegments` fail.
This PR adds [shunit2](https://github.com/kward/shunit2) as a git submodule and execute the unittests in `test/powerlevel9k.spec` with [Travis-CI](https://travis-ci.org). Btw. …
=> Add Unit tests

README.md, powerlevel9k.zsh-theme
Prior to this, the rbenv prompt only showed something if the
`$RBENV_VERSION` environment variable was set. This was not a complete
solution because rbenv can be configured locally, per directory, with
dotfiles. When using dotfiles, the `$RBENV_VERSION` variable is not set.
This fixes the issue by taking the output of the `rbenv version-name`
command which shows the real rbenv version being used based on any of
the 4 ways to change rbenv as shown here:
https://github.com/rbenv/rbenv#choosing-the-ruby-version
This commit also adds documentation to the README that describes the prompt.
Fixes issue #215 
Thanks to @MatthewMDavis for the original version of the patch: https://github.com/MatthewMDavis/powerlevel9k/commit/96a8408a0c27ed6dc10dfa8829a549419ab5d4ec
=> Improve the rbenv prompt by using `version-name`

functions/vcs.zsh, powerlevel9k.zsh-theme
The VCS segment defined on every piece the foreground color itself. That was from a time when I wanted to emphasize more relevant information by a stronger color. Other informations needed therefore to be displayed in weaker colors (like "dark grey" instead of "black").
Here I removed this completely, so the dynamic overriding mechanism can take place.
This fixes #213. Thx @bartlibert for the report.
=> Fix vcs foreground color

.travis.yml, CHANGELOG.md, functions/vcs.zsh, powerlevel9k.zsh-theme, test/segments/vcs.spec
The default state is now `clean`.
Bonus:
The regular expression for the untracked state did not work correctly on OSX. This is now fixed.
=> Rename vcs default state

README.md, powerlevel9k.zsh-theme
New PR based off `origin:next` instead of `origin:master` see #227 
Add new `chruby` prompt to show ruby version using `chruby`.
Update the README accordingly.
See postmodern/chruby#245 for issue with auto switching ruby version using `.ruby_version` file.
Partially closes #119 , replacement for #227.
=> Add chruby prompt

powerlevel9k.zsh-theme
This commit changes nvm prompt setup to return immediately if no node
version is installed/available.
Currently, prompt shows incorrect global node version _one_
Specifically, if you install nvm (from brew or manually) and do not have
global node installed (or set), then the prompt shows `${node_version:1}`
which evaluates to the string `one`. This is incorrect, and nvm should not
show anything. This commit ensures this by immediately returning if
`nvm current` returns "none".
=> Fix NVM prompt to return if not used

README.md, functions/icons.zsh, powerlevel9k.zsh-theme
I don't know if you are interested in adding new simple segments? (especially since we can add new custom segments easily).
But in case, this PR add a new segment for display the current active Docker Machine.
=> Add a new segment for current active docker machine

README.md, functions/utilities.zsh, powerlevel9k.zsh-theme
Finally got around to re-implementing #140 without using the `jq` tool, and against the current `next` branch so it can be pulled in easily.
I'm happy to pull the comments out if you'd prefer; I just left them in now because they were in my original implementation.
=> Add shortening strategy based on package.json name

functions/vcs.zsh
Copy of #234 on right branch.
[1]: https://github.com/nmaggioni/powerlevel9k/blob/next/functions/icons.zsh#L201
=> Git tag not replacing branch

README.md, powerlevel9k.zsh-theme
Shows the currently active anaconda environment different from root.
Requires `ack` or a recent version of `grep` supporting positive lookbehind.
=> Add anaconda segment.

powerlevel9k.zsh-theme
The jobs -l command displays a "pwd now :..." line when a job was launched from a different directory than the current one that cause powerlevel9k to display an incorrect number of background jobs. This change fixes it.
=> Fix incorrect background jobs number

powerlevel9k.zsh-theme
Now it is possible to set the installation path by setting `POWERLEVEL9K_INSTALLATION_PATH`. If set, this path will always be used. If it was not set manually, we try to determine the path automatically.
This fixes #264 
@protist could you double-check? Especially with your ZSH 5.0.7. That would be great. Thanks.
=> Refactor location installation path code

functions/icons.zsh, powerlevel9k.zsh-theme
Rust, Ruby icon already support, I'm so susprise why virtualenv still don't have icon.
I get Python icon Unicode from here: https://vorillaz.github.io/devicons/#/cheat
NOTE: This is re-submmit PR of #257
=> PYTHON ICON for virtualenv prompt

powerlevel9k.zsh-theme
Currently you can't make a conditional custom segment. This changes the
prompt_custom function responsible for printing custom segments so that
it won't print the segment in case the content is empty.
With this it becomes possible to make conditional custom prompts simply
by making it not print anything when it's not supposed to be shown.
This is in response to my own issue #267 about a way to make custom segments conditional without having to monkey patch anything. 
I first imagined adding a new var `POWERLEVEL9K_CUSTOM_NAME_CONDITION` with a condition that could be evaluated and used as a conditional, but @Tritlo insightfully suggested that it would be way simpler to just test if the custom command returned an empty string and only print the segment in case it didn't.
=> Make prompt_custom not print the segment if empty

README.md, powerlevel9k.zsh-theme
I created a new segment for use with pyenv to manage python versions. This prompt can be used in place of `virtualenv` segment, however, it is targeted at users of [pyenv](https://github.com/yyuu/pyenv) and not meant to replace the `virtualenv` segment.
The prompt works by parsing output of `pyenv version` and displaying the first word of the output as segment text. The design (color etc.) is same as the `virtualenv` segment to respect consistency. The segment would need to be revisited if `pyenv version` changes its output format. ~~Furthermore, a small change would be required if and when PR #260 is accepted to include python icon for the segment.~~ The python icon is now added to the prompt.
Tested on my personal machines (Mac OSX 10.11.4 and Ubuntu 15.04). Feel free to reword the …
=> Add pyenv segment to show active non-system python version

powerlevel9k.zsh-theme
This ensures that the following package.json extract would just give the
prompt "foo" rather than "foo\nbar".
{
"name": "foo",
"author":
{
"name": "bar",
}
}
Fix of PR #273
=> Only match first name in package.json

powerlevel9k.zsh-theme
`git rev-parse --git-dir` returns just `.` when in the top level of
a`.git` directory. This would cause a problem when extracting the
package_path. Closes #271. Fix of PR #274.
=> Handle shorting path when in the .git directory

README.md, functions/vcs.zsh
Added variable to control the hiding of tags as too many tags can lead to a whole line taken up with just the git information.
=> Added POWERLEVEL9K_VCS_HIDE_TAGS variable to hide tags

powerlevel9k.zsh-theme
Spaces in directory names currently will cause truncation
=> Handle spaces in path when shortening

functions/icons.zsh
Some unicode icon strings were set with \uHHHHH which showed the wrong
characters on some implementations of zsh (linux and macOS).  Changed
\uHHHHH to \UHHHHH and conversely changed \UHHHH to \uHHHH.
=> Changed \u and \U to reflect number of hex digits to follow

functions/vcs.zsh
This is on Linux Mint 17.3, with zsh 5.0.2 (x86_64-pc-linux-gnu).
If you navigate to a SVN directory, it shows something like the following:
```sh
+vi-svn-detect-changes:local:1: not valid in this context: Gemfile.lock         
 ~/D/D/C/w/qa X=''
X=''
'?'=0
Performing=''
status=0
on=''
external=''
item=''
at=''
Performing=''
status=0
on=''
external=''
item=''
at=''   
```
Per a similar workaround described in this issue https://github.com/zsh-users/zsh-autosuggestions/issues/127#issuecomment-188513043, you can just wrap the call in quotes.
=> Fix '+vi-svn-detect-changes:local:1: not valid in this context'

README.md, powerlevel9k.zsh-theme
Adds functionality with a toggle to show the OK identifier displayed in verbose mode in non-verbose mode too.
=> Show OK in non verbose status prompt

functions/utilities.zsh, test/segments/dir.spec
Truncate the path from the right by taking in account the delimiter length, so that directories with names shorter than truncated name + delimiter aren't incorrectly truncated.
For example, if `SHORTEN_DIR_LENGTH` is 4 and the delimiter is `..``, `../tests/..` and `../custom/..` are not incorrectly "truncated" to `../test../..` and `../cust../..`, both of which are longer or the same length as the original untruncated directory names.
=> Consider delimiter length while right truncating directories

CHANGELOG.md, README.md, powerlevel9k.zsh-theme
Now the path separator is configurable. You just need to set `POWERLEVEL9K_DIR_PATH_SEPARATOR` to whatever you want.
As you can see, the change is independent from the shorten strategy. So these can be combined in every way. 
Further, you could even change the color for that separator. In my case is used the following setting:
```zsh
POWERLEVEL9K_DIR_PATH_SEPARATOR="%f "$'\uE0B1'" %F"
```
=> Configurable path separators

README.md, functions/icons.zsh, powerlevel9k.zsh-theme
This commit will add a prompt for the current installed swift version. As soon as the PR is merged, I will add a configuration example to the [Wiki](https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config).
=> Add prompt for current installed swift version

README.md, powerlevel9k.zsh-theme
I added a feature to the context segment to allow for customizable host depth on the prompt as outlined in the ZSH documentation here - http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Login-information. I use p9k across a range of servers across a range of sites at work and being able to customize the host depth to include the site is immensely helpful. Thought this might be useful to other folks too!
=> Context host depth

CHANGELOG.md
This fixes #363 
See https://github.com/bhilburn/powerlevel9k/compare/v0.5.0...master
Also, I added `pyenv` segment to v0.4.0 changelog. We missed that..
=> Add Changelog for v0.5.0

README.md, functions/icons.zsh, powerlevel9k.zsh-theme
@bhilburn mentioned in #365 that he would be interested in a public ip segment, i hacked one together for review/discussion on behavior/icons/etc. Currently it will only poll for a new IP every 5 minutes which is configurable by the user. It saves the IP to a tmp file also configurable by the user. It will attempt to use dig to get your IP if it's installed, if not it will use either curl or wget to poll an IP checker host in the same manner that neofetch uses. Let me know what you all think.
=> Public ip segment

CHANGELOG.md, README.md, functions/icons.zsh, powerlevel9k.zsh-theme
Okay, this is the revamped version of #352. I cherry-picked @anion155's commits onto a new branch and modified the behavior somewhat. It currently shows the usage level of the partition that your CWD resides on. I think it would be nice to make it possible for users to peg the segment to a specific partition, but that can be a future enhancement. Here is what it looks like:
It's working fine on my Linux system. It would be great to have a test from an OSX user, as well as a general code review.
=> Anion155's hdd_usage segment

powerlevel9k.zsh-theme
The regex for the swift segment matches too much (matched the "86" from `x86` as second). Here I simplified it to match the first number as this is probably the "main" version number. I assume the original creator of this segment (@thomaspaulmann) wanted the first number only (see https://twitter.com/thomaspaulmann/status/806078915546664960).
Before it matched:
The new one just matches:
@thomaspaulmann This is probably the reason, why you coded `swift_version` as array. But this way it is simpler IMHO.
Disclaimer:
I found this issue in #344 and couldn't reproduce it there in a proper unit test. But it prevented other segments from rendering.
=> Fix swift segment

powerlevel9k.zsh-theme
If the tempfile already exists and CLOBBER is not set, a file exists error occurrs. This commit avoids this problem. See http://unix.stackexchange.com/questions/212127/zsh-disable-file-exists-warning-with-redirection
I backported this fix from #344.
=> Avoid error if CLOBBER is not set

powerlevel9k.zsh-theme
There is a bug with `truncate_with_package_name` truncation strategy if the repo is symlinked. I encountered this bug, when writing a test for that strategy in #344 , as the temp dir in OSX is actually a symlink to `/private/tmp`.
The problem is that `git rev-parse --show-toplevel` always shows the real path on the file system that, if symlinked, is not the root path to the repo. Despite that using `git` to find the root path of a repository, where potentially a `package.json` lies is not the best way, this PR just fixes the truncation problem. A better way would be going up a directory, until a package.json is dicovered (similar to @BenoitAverty approach in #353).
In a folder `/tmp/repo/1/12/123/1234/12345/123456/1234567/12345678/123456789`, with a `package.json` in `/tmp/repo` the …
=> Fix error with truncating package name if repo is symlinked

README.md, powerlevel9k.zsh-theme
I changed the `POWERLEVEL9K_PUBLIC_IP_METHOD` to an array. That way the code could be simplified a lot.
/cc @rjorgenson
=> Simplify `public_ip` segment

prompt_powerlevel9k_setup
ZSH has the ability to preview and set themes directly from the `prompt`
builtin. To do so, the theme must be in FPATH and named
"prompt_theme_setup".
This PR adds a symlink pointing `powerlevel9k.zsh-theme` to `prompt_powerlevel9k_setup`. For full compatibility with `prompt` builtin, we still need to add our functions to `FPATH` though.
=> Fix theme for use with plain "prompt" command

README.md, functions/utilities.zsh, powerlevel9k.zsh-theme, test/segments/dir.spec
This adds @BenoitAverty `truncate_with_folder_marker` strategy for the `dir` segment.
=> Add "truncate_with_folder_marker" shorten strategy

README.md, powerlevel9k.zsh-theme, test/powerlevel9k.spec, test/segments/dir.spec
As @Hebgbs suggested in the chat, here is the option to omit the first character in dir segment.
Before (with `POWERLEVEL9K_DIR_PATH_SEPARATOR` set):
After:
@Hebgbs Could you confirm that this is what you wanted?
=> Add ability to omit the first character in dir path

.travis.yml, CHANGELOG.md, README.md, functions/icons.zsh, powerlevel9k.zsh-theme, test/segments/command_execution_time.spec
This PR solves #330 . It is not complete by now, just wanted early feedback.
Still missing:
=> Add command execution time segment

functions/icons.zsh
This doesn't do anything regarding the bigger issues of #97, but it's a short-term fix for people using patched/complete nerd fonts. I added the 'nerd-patched-complete' method to the icons with updated codepoints that reflect the current state of the nerdfonts with relocated octoicons. Maybe until things settle down this can just remain open and people can pull it in as a patch. I haven't tested this extensively, but the few pre-patched nerd fonts whose codepoints I checked against seemed to line up correctly.
=> Add nerdfont icons

functions/vcs.zsh
Hi,
Sorry for coming with this so late in time. But  I missed some details when calling `git ls-remote`, this fix git ls-remote call; match [suggested code](https://github.com/bhilburn/powerlevel9k/pull/360#discussion_r93804449) for redirect errors to null when no origin is in git repo.
Related to [PR 360](https://github.com/bhilburn/powerlevel9k/pull/360)
thanks!
=> Hide error when no origin in git repo

TESTS.md, test-bsd-vm/Vagrantfile, test-bsd-vm/bootstrap-zero.sh, test-bsd-vm/bootstrap.sh, test-vm-providers/plain.sh, test-vm/Vagrantfile, test-vm/plain.sh
This PR adds a BSD box, so we can easily test P9K there (like #415 and #422). Works the same as the ubuntu VM.
I want to move the other ZSH-Framework-Providers into the share `test-vm-providers`, so that we can install that frameworks in the BSD machine as well.
You need to install [vagrant](https://www.vagrantup.com/) and [VirtualBox](https://www.virtualbox.org/).
1. Go into the according directory (either `test-vm` or `test-bsd-vm`)
2. Type `vagrant up` in your terminal (may take a while at first startup)
3. SSH into the machine via `vagrant ssh`
4. When you are done, log out of the machine and type `vagrant halt`
=> Add FreeBSD VM

CHANGELOG.md, README.md, powerlevel9k.zsh-theme
This PR is based on #411 and should be merged after it.
Now when `truncate_with_package_name` is set, we search for a `package.json` and - if not found `composer.json` and parse the "name" field out of it. The order and the search files itself could be specified by setting `POWERLEVEL9K_DIR_PACKAGE_FILES` (defaults to `(package.json composer.json)`).
Fixes #349
=> Truncate via name in composer json

functions/icons.zsh
New pull request with missing nerd-fonts icons
Sorry, my previous one https://github.com/bhilburn/powerlevel9k/pull/439 was made from an outdated fork
=> added missing icons

functions/icons.zsh
Now the icons are sorted alphabetically, and the users icon overrides are taken into account (by default). If `get_icon_names` is called with "original" as parameter, it prints the original icons.
=> Sort the output of `get_icon_names` alphabetically

.travis.yml, functions/icons.zsh, test/functions/icons.spec
I added a default `LC_CTYPE` setting to protect special characters. Interestingly we had such settings already in `functions/icons.zsh`, but for some modes this setting got lost.
This should fix #442 (already fixed by workaround).
In addition I added some tests to check if Icons were added in all modes (see #448 ). The tests fail because of that. Once the missing icons got added, the tests should work. ;)
=> Protect special characters in various modes

README.md
* Remove a duplicate in the table
* Use word "set" to emphasize $USER as a shell variable
Closes #447.
=> README: context section typo fix (#447)

powerlevel9k.zsh-theme
In Emacs, `M-x shell` creates a shell buffer with *very* rudimentary terminal capabilities. `$TERM` is set to `dumb`, and `echotc Co` fails after printing `echotc: no such capability: Co` to standard error. If our goal was to determine whether the terminal supports 256 colors, we really have no information to go on. I recommend that we trust the user and hope for the best. That means we should (1) discard any `echotc Co` error output, and (2) forego the warning message about having fewer than 256 colors if `echotc Co` failed.
=> Gracefully handle `echotc Co` failure

README.md, powerlevel9k.zsh-theme
Replaces `~` at the beginning of the directory for `dir` prompt, just like `/`. Not sure about the variable name, please tell me if you have a better idea :)
=> Make home shorthand configurable for dir prompt

powerlevel9k.zsh-theme
So the tick will not be too bright in light background color scheme such
as Solarized Light.
=> Set tick to color name green instead of color code

powerlevel9k.zsh-theme
This is a workaround for https://github.com/bhilburn/powerlevel9k/issues/312 I've just added custom svn prompts instead of using our primary ones. The problem is the `%b`-identifier. When we use the `%b`-identifier for svn it seems to break our color-encoding. I guess they use some chars in there or some custom color encoding that will  break ours. The `%b`-identifier will give for SVN the following output:
`<branch-name>:<revision number of branch>`
When I use `%b` everything after `<branch-name>` will be yellow..I tried to fix the color with it. But maybe someone else has more luck.
It's sad that we lose the branch-name for this feature. But I think most people use only one branch with svn and we still display the revision-number. So it shouldn't be that bad. Let's focus on `git`. :) …
=> [SVN] removed %b identifier to fix color encoding

powerlevel9k.zsh-theme
Fixes #445 
Because PROMPT and RPROMPT are in double quotes, they expand the shell commands inside them. Because prompt_subst is set, whatever these commands expand to will also be expanded when the prompt is displayed.
This fixes the problem by using single quotes, ensuring that they are only expanded once, on prompt display.
=> Fix double expansion of prompt variables

powerlevel9k.zsh-theme
I'm not sure why I didn't think of this before, but there's no point in doing all this realpath/perl/whatever magic when there's something built in to zsh which does all this for us. 
The only question is whether to use the A or P modifier.
http://zsh.sourceforge.net/Doc/Release/Expansion.html#Modifiers
This supercedes #482.
CC @dritter
=> Use method built in to zsh to read symlinks

powerlevel9k.zsh-theme
Firstly, `prompt_opts` needs to be set so `prompt_subst` and other prompt related options will be set consistently when this prompt is used. We also need to set them manually for when the script is executed directly (or when prompt_powerlevel9k_setup is called directly). This workaround is based off the same workaround in pure (https://github.com/sindresorhus/pure/blob/3a08df333d1a32b5be610f3cb688d5c773b8c650/pure.zsh#L397) which was based off the code from the prompt function in zsh, as seen below:
```
prompt () {
local prompt_opts
set_prompt "$@"
(( $#prompt_opts )) &&
setopt noprompt{bang,cr,percent,subst} "prompt${^prompt_opts[@]}"
true
}
```
This introduces a complication... lots of prompts do this:
```
setopt LOCAL_OPTIONS
unsetopt XTRACE KSH_ARRAYS
```
I assume when starting off, …
=> Fix some oddities with prompt options

powerlevel9k.zsh-theme
this fixes the broken prompt mentioned in https://github.com/bhilburn/powerlevel9k/issues/500
=> [detect-virt] quickfix for unnecessary information in prompt

functions/icons.zsh, functions/utilities.zsh, powerlevel9k.zsh-theme
Windows icons! See my comment here about the 32-bit refix:
https://github.com/bhilburn/powerlevel9k/pull/480#issuecomment-299676867
=> Icons for Windows/Cygwin + Refixes 32-bit support

README.md, powerlevel9k.zsh-theme
Added new option (POWERLEVEL9K_STATUS_SHOW_PIPESTATUS) that shows
the status for all piped commands, not just the right-most.
Closes #514
=> status: add option for support pipes

README.md, functions/icons.zsh, powerlevel9k.zsh-theme
This works only for `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`.
It can't work for the right-hand prompt (`RPROMPT`) because multi-line is handled
via terminal trickery (moving the cursor and restoring it).
This is against the `next` branch as requested by @bhilburn on #518
@bhilburn asked:
> 1. What happens if the user turns this on and also turns on PROMPT_ON_NEWLINE?
> 1. Can you file against `next`? ;)
> 1. We should be sure to add a bit about this to the Wiki once it is merged.
> 1. Is there any limit to the number of times you can use this segment in a prompt?
1. It works, but it doesn't have the appropriate ansi art in first two characters... Let me see if I can fix that.
1. Done!
1. 👍 😃 
1. Nope.  It works all you want, though it it can look silly. :smiley:
=> "newline" segment

powerlevel9k.zsh-theme
This disables the hooks.  If you try to change the prompt (e.g. `PROMPT='$ '`) then
it'll revert right back to powerlevel9k because the hooks rebuild the `PROMPT`s.
Usage:
``` sh
OSX > ~/.zgen/bhilburn/powerlevel9k-master > pr/teardown ↑1 >
✓ > prompt_powerlevel9k_teardown
lithium% echo "look ma, no powerlevel9k prompt"
look ma, no powerlevel9k prompt
lithium% prompt_powerlevel9k_setup
OSX > ~/.zgen/bhilburn/powerlevel9k-master > pr/teardown ↑1 >
✓ >
```
=> add function to disable powerlevel9k hooks

powerlevel9k.zsh-theme
This is also (marginally) faster than before.
As a side-effect of these changes, it won't trigger nvm if you're using the zsh-nvm plugin and have lazy loading set.
With the previous code, there was no point to setting lazy load because the prompt would load it immediately.
@bhilburn said on PR #516
> Not being a nvm user, or even a Node.js developer, myself, I'm not knowledgeable enough to review the code. That said, a couple of items:
>
> 1. Would you mind re-submitting this PR against next?
> 1. What happens if nvm isn't loaded due to the lazy loading bit you mentioned above? Does the segment just not print (fail gracefully)?
>
> I'd like to get @dritter's review on your new PR because I believe he is a Node.js user? ;)
1. Done!
1. Correct.  The segment isn't printed if `nvm` isn't …
=> nvm: improve default detection

powerlevel9k.zsh-theme, test/segments/go_version.spec
As of Go v1.8 GOPATH need not be set, as it will default to $HOME/go. By using `go env GOPATH` to retrieve the value first, this technique will work regardless of whether GOPATH is currently set by the user.
=> Only show go_version segment if inside GOPATH

.travis.yml, functions/icons.zsh, powerlevel9k.zsh-theme, test/segments/kubecontext.spec
I created this little addition locally and thought someone else might enjoy this. It's the current context of your `kubectl` config. Whatever your current is set to it will show in the prompt with the Unicode [Helm](http://www.fileformat.info/info/unicode/char/2388/index.htm) symbol.
Let me know if I need to add anything else or change the function!
=> Added kubectl config's current context

powerlevel9k.zsh-theme
This resolves issue #553 when prompt hangs on `kubectl version`
=> Fixed prompt hangs on kubectl version command

powerlevel9k.zsh-theme
Having a username with a dash, such as mine, `d-side`, currently results in RVM segment displaying the wrong thing, e. g. `side/.rvm/rubies/ruby` (for `MY_RUBY_HOME=/home/d-side/.rvm/rubies/ruby-2.4.1`).
This is a kind of a dirty fix for the issue, I just forced `awk` to grab the last column, instead of 2nd. I'm not particularly fond of this approach, but this does work for my cases and doesn't (probably) introduce additional breakage.
Additional suggestions welcome.
=> Fixed RVM segment for usernames with dashes

powerlevel9k.zsh-theme
- Used ZSH built-in magic to get the installation directory.
- Works with symlinks.
- No longer calls out to external program 'dirname'.
- Fixed issue with spaces in the path.
- No longer leak the variables 'filename' and 'script_location'.
If this fails to work, then ZSH itself is broken.  The error handling is no longer needed.
=> Cleaned up installation directory detection

CODE_OF_CONDUCT.md, functions/icons.zsh, powerlevel9k.zsh-theme, test/segments/go_version.spec
List of commits:
- 82f319d
> Adding Code of Conduct
>
> Slightly modified version of Contributors Covenant.
- 65c7706
> Fixed RVM segment for usernames with dashes
>
> Having a username with a dash, such as mine, `d-side`, currently results in
> RVM segment displaying the wrong thing, e. g. `side/.rvm/rubies/ruby`. This
> fixes the issue.
- f81ecc1
> set GO_ICON manually in test
- a6887eb
> update test
- 99c9ba9
> add Gopher icon to go_version segment
=> Merge in commits from master

test-in-docker
Certain frameworks don't work with the containers for reasons such as ZSH version or git versions.
=> test-in-docker: show known issues

powerlevel9k.zsh-theme, test/segments/dir.spec
This was partially an experiment on my part; I wanted to see
what would be involved in (safely) replacing some sed calls.
The rational is that forks out to sed are slower than pure ZSH.
It isn't a huge difference on Linux, but each fork can take a while even in
the latest Windows.
...and as I said, it was an experiment.  I'm interested in optimizing some things.
=> Added tests and replaced a sed call

powerlevel9k.zsh-theme
Update of the vpn prompt to use /sbin/ifconfig instead of ip
=> vpn prompt: change "ip" to "ifconfig" to be used on OSX

functions/utilities.zsh, test/segments/dir.spec
Even if the delimiter is empty, the min length should be 1. This works on OSX and BSD.
Fixes #558
=> Fix empty delimiter

functions/icons.zsh
While using awesome-terminal-fonts it is recommended to use `\ue63c` to
reference python icon instead of `\U1F40D` (that wasn't even working).
Ref:
https://github.com/gabrielelana/awesome-terminal-fonts/issues/38#issuecomment-302939451
=> Fix reference for Python icon.

powerlevel9k.zsh-theme
**Changes**
* Fixed an issue that Vi mode won't appear before the user changes the mode. (This change shows INSERT when failed to get current Vi mode)
* ~Added nice-exit-code plugin. This can be activated with the flag `POWERLEVEL9K_STATUS_NICE_EXIT_CODE` and shows a signal name of the last status code.~
=> Fixed Vi mode indicator issue

README.md, powerlevel9k.zsh-theme
This makes signal exit status easy to understand.  Instead of just
showing exit code "137", you now see "KILL(-9)".
Based on #580 by @sei40kr (thanks!)
=> status: show signal name

README.md, powerlevel9k.zsh-theme
When variable POWERLEVEL9K_DIR_SHOW_WRITABLE is set to true, dir prompt
will have new state NOT_WRITABLE.
This state will be set when user doesn't have permission to write in
current working directory as in prompt dir_writable.
When mode that allows icons is set, LOCK_ICON is used.
Closes #588.
=> Implemented functionality from dir_writable to dir

powerlevel9k.zsh-theme
In 5.4.1, this option was reset between prompts, so to retain the
previous default behavior, this should be added back.
This was the change which caused it to be reset: https://github.com/zsh-users/zsh/commit/43e55a9bcd2c90124a751f2597d2f33cb6e3c042#diff-bb10d67e7a8561b66a53a805f3c77a40R233
This is the documentation on the option itself: http://zsh.sourceforge.net/Doc/Release/Options.html#Prompting
Note that this makes it a little harder to unset this option (as it needs to be done after setting the prompt) but that seems fine, as all the other prompt options are already this way.
=> Add back the prompt_sp option for zsh >= 5.4.1

functions/icons.zsh
This is basically https://github.com/bhilburn/powerlevel9k/pull/472 but with the requested changes. I spent some time today getting this working for me and thought I would share my results. This creates a new icon set called `awesome-mapped-fontconfig` so it won't break for any existing users. This relies on the user sourcing the font mapping files in their shell startup scripts, as recommended by: https://github.com/gabrielelana/awesome-terminal-fonts#font-maps. It does a simple check to ensure the fonts maps were sourced, and logs a warning if they weren't.
=> similar to PR #472, fixing for awesome font mappings

powerlevel9k.zsh-theme
Removed duplicate code selecting which load average to use.
Fixed load average selection being in OSX/BSD part of if, making it not work
on non OSX/BSD systems.
Optimized actually getting the load average.
=> Fix average selection in load segment.

powerlevel9k.zsh-theme
Same issue as here and same fix:
https://github.com/bhilburn/powerlevel9k/commit/bddbdd62e841d6e008e95fe2f0909d5b32e623a8
=> Fix prompt_kubecontext:local:1: not valid in this context: Version:

powerlevel9k.zsh-theme
Signed-off-by: Hal Gentz <zegentzy@protonmail.com>
=> Fixes issue #619

powerlevel9k.zsh-theme
The OSX date command does not have the -r option for getting the last modification time of a file. The stat command is being used instead.
=> OSX bug fix for prompt_public_ip

powerlevel9k.zsh-theme
Prevents warning messages from zsh
=> declared variables as 'local'

powerlevel9k.zsh-theme
- Modify prompt_dir function to set current_path based on pwd and
replace $HOME with ~
=> ISS-650 Fix PYTHONPATH appearing in prompt

powerlevel9k.zsh-theme
`AWS_PROFILE` env var has been respected by AWS client as well as `AWS_DEFAULT_PROFILE`. See here: http://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
This small change adds `AWS_PROFILE` in coalesce with `AWS_DEFAULT_PROFILE`
=> Add support for both AWS_PROFILE and AWS_DEFAULT_PROFILE

powerlevel9k.zsh-theme
=> Kubernetes segment shorter if possible

functions/vcs.zsh
If user defined alias of grep command with '-r' or '--recursive'
option, it causes a slow response of command line. It is not
unexpected behavior of vcs info.
This commit explicitly disables alias of grep to suppress side
effects.
=> vcs: Disable alias of grep to fix performance penalty

functions/vcs.zsh
Some self-hosted Bitbucket Server instances still use 'stash' in the naming convention for servers and endpoints. Whilst this is a preferential change, it should cause no harm to have Stash or other self-hosted Bitbucket servers use the Bitbucket icon, as opposed to the generic Git icon.
=> Add Stash naming support for Bitbucket Server

powerlevel9k.zsh-theme
Whitespaces in Path lead to an error in ´prompt_dir()`. To fix this, the IFS variable which defines the split-chars for assignments is temporarily set to an empty string.
=> Fixed Issue with whitespaces in path.

powerlevel9k.zsh-theme
My latest PR #676 seemed to have been incompatible with #661 - I did my PR on top of master instead of next. This one is done on top of next and should fix the current not so great state of next (prints nothing). Sorry!
=> Fix of k8s shorter segment

powerlevel9k.zsh-theme
Adds `REMOTE` state to color prompt with in case of a shell over ssh.
This state has lower priority than `ROOT` state to not lose the privilege warning.
=> Add remote state to context prompt

README.md, functions/colors.zsh, powerlevel9k.zsh-theme, test/segments/rust_version.spec
terminals do not always render named colors
when using parameter expansion.
- check if named color renders (dynamic)
- if not use the colorCode
- getColorCode executable with (foreground|background) to show example in terminal
- only 2 places render colors, so it is an easy fix.
https://github.com/bhilburn/powerlevel9k/issues/702
=> [next] -- fix for colors

powerlevel9k.zsh-theme
Replace PUBLIC_IP_ICON with VPN_ICON if $POWERLEVEL9K_PUBLIC_IP_VPN_INTERFACE is set and up. It allows to check quicker if the VPN is up or if the public IP is already a registered ip.
=> Replace PUBLIC_IP_ICON with VPN_ICON if VPN is up

README.md
As it stands, using `vpn` in .zshrc returns the error `bash: prompt_vpn: command not found...`.
`vpn_ip` is the correct term.
=> Corrected VPN IP command

functions/colors.zsh
This was causing colors specified as numbers to not be shown.
=> getColor() must always print result

powerlevel9k.zsh-theme
Hi,
I sometime, have hosts that do not have `bc` program installed. The load widget use bc for doing math that zsh can easily handle.
This PR replace math done with `bc` by math done with zsh.
Best regards.
=> fix: Remove dependency of bc for load widget

functions/colors.zsh, powerlevel9k.zsh-theme
Hi,
I needed the possibility to disable the warning message, which occurs when a terminal with less than 256 colors is used. For that reason I added the `POWERLEVEL9K_CHECK_TERM_COLORS` environment variable for disabling the message.
Best Regards
=> Added flag for checking the term colors

functions/icons.zsh
VCS_GIT_ICON and VCS_GIT_GITHUB_ICON were wrong.
=> Fix GIT and GITHUB nerdfont icon.

README.md, powerlevel9k.zsh-theme
I believe [this commit](https://github.com/bhilburn/powerlevel9k/commit/520eed12482b276e630d66b01a3f5852c96b6b1f) stopped the vi_mode plugin from working (also see [this comment](https://github.com/bhilburn/powerlevel9k/issues/319#issuecomment-355870476) from issue #319).
This PR returns one of the parts that was removed in that commit to get vi_mode working again as suggested by the comment linked above.
It also adds a check to see if `POWERLEVEL9K_VI_INSERT_MODE_STRING` is an empty string and if so, it skips showing the segment entirely.
This works both when using vi mode directly and when temporarily entering vi mode from emacs mode with `^X^V`.
This fixes #725 and possibly #319.
=> Fix vi-mode and support hiding segment when in insert mode

powerlevel9k.zsh-theme
This fix allows the user to see the "little blue triangle" that is created when iTerm2 shell integration is enabled.
=> Fix iTerm2 integration with PowerLevel9k

README.md, powerlevel9k.zsh-theme
There were a few ways to do this - I have no idea about which ways yield the best performance (tbh I'm not very familiar with bash scripting, but I just assume the less pipes the better).
I've also included an alternative implementation which seems to work - but for some reason, the implementation of every other truncation option doesn't use stuff like `%~` and surely there must be a reason, which is why I've commented it out.
I'm sure I could work on this a bit more to give it more customizability - I've just implemented it so that I can get my prompt to appear how I want. As a sidenote, I definitely think that the dir configuration options could be refactored and made more powerful and easier to use.
=> Add absolute truncation option to dir segment

README.md, functions/icons.zsh, powerlevel9k.zsh-theme
Before I discovered zsh, I was using oh-my-bash. What I missed from that was that if I still had elevated privileges that I could see that. This adds the state of `SUDO` to `user_prompt` which gives this capability.
=> Added sudo state to prompt_user

powerlevel9k.zsh-theme
`$pipestatus` is returning all zeros when using `[[  ]]` expressions
that are false.
This works around it by using `$status` (A.K.A. `$?`) when `$pipestatus`
has only 1 items.
Fixes #749
=> workaround for ZSH status behavior

README.md, powerlevel9k.zsh-theme
When navigating to a sub-folder of $HOME and then back up to $HOME, the shortened directory incorrectly contains the shorten delimiter (`cd; cd Documents; cd ..;'` results in `.../~` as the directory shown). This only seems to occur if the shorten strategy environment variable is left blank.
To solve this I added a conditional check to apply the default switch statement case only if the current_path is not $HOME (i.e. not equal to "~").
Just in case this may be more specific to my configuration, my PowerLevel9K config is shown below:
```export DEFAULT_USER=conrad
export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir_writable dir ssh anaconda vcs)
export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator time) 
export POWERLEVEL9K_STATUS_VERBOSE=true
export …
```
=> Fixed home abbreviation not being exclusive with circular navigation

functions/colors.zsh, functions/utilities.zsh, powerlevel9k.zsh-theme
This is a rather small change. I recently stumbled upon the option `setopt WARN_CREATE_GLOBAL` that 🙄 warns about creating global variables. With this PR I made all unnecessary global variables local.
=> Make variables local

README.md, powerlevel9k.zsh-theme
- Add environment variable POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW to set the rbenv prompt segment to show if the local Ruby version is the same as the global Ruby version.
- This also includes a small bugfix where $(which rbenv) would return the actual function, so $(command which rbenv) returns the result of calling the function.
- Update Readme with description for setting POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW
=> Rbenv prompt option always displays #777

README.md
The default value for Public IP file in the readme was referencing `/tmp/p8k_...` rather than `/tmp/p9k_...`
=> Update default public ip file name

.travis.yml, CHANGELOG.md, README.md, functions/icons.zsh, functions/utilities.zsh, functions/vcs.zsh, powerlevel9k.zsh-theme, test/powerlevel9k.spec, test/segments/command_execution_time.spec, test/segments/dir.spec, test/segments/go_version.spec, test/segments/kubecontext.spec, test/segments/laravel_version.spec, test/segments/rust_version.spec, test/segments/vcs.spec
This is a staging branch to be merged in `next`. 
It includes the following changes (in order of merge):
- `master`. For easier merging later on, `master` was merged in first. There were two conflicts, one being a conflict in the `README.md` (#781 vs #684) and another one in the `powerlevel9k.zsh-theme` (#795 vs #610). The latter one being the more impacting one, as I had to drop one completely (both implemented the same thing). I went with #795, even this one is more recent. The reason for that is that this commit is the one on `master`, and I don't want to deprecate a variable just for naming reasons (or the naming must improve vastly, which didn't here).
- #797. Conflicts: `functions/vcs.zsh`: Two commits avoided wrapper behaviour. #685
in grep, #797 in git.
- #798
- #783 Conflicts: …
=> [WIP] Staging 0.6.5

README.md, functions/vcs.zsh, test/segments/vcs.spec
These changes allow truncating of vcs branch name.
Before:
After:
@bhilburn, please take a look.
=> Add vcs branch name truncating.

powerlevel9k.zsh-theme
Hides the battery segment if percentage hits 100%
=> add new option "POWERLEVEL9K_BATTERY_HIDE_ABOVE_THRESHOLD"

functions/icons.zsh, powerlevel9k.zsh-theme
This PR adds a new setting for the `dir` segment to style `/etc` and subfolders independently
It also adds a default Icon to use `\uF013` (only if you are using font-awesome or nerd-fonts config)
Options to change colors and icon:
```
POWERLEVEL9K_ETC_ICON='\uf0ad'
POWERLEVEL9K_DIR_ETC_BACKGROUND='57'
POWERLEVEL9K_DIR_ETC_FOREGROUND='white'
```
Example Screenshot:
=> add cog symbol to dir segment if folder is /etc*

functions/utilities.zsh
The diff is pretty self explanatory. I changed the switch-case so that it will actually pick up the keywords. Tested to be successful on OpenSUSE Tumbleweed.
Hoping for this feature to be pushed to master soon :smile:
=> Fix Linux distribution detection

powerlevel9k.zsh-theme
Maybe the original author happened to name their context `k8s_namespace` 🤔
=> kubecontext: fix context, namespace comparison

functions/vcs.zsh
This prevents `git` command from passing through eventual aliases, commonly defined when Git wrappers (e.g. hub) are used.
=> Fix wrapper slowness in vcs segment

README.md, powerlevel9k.zsh-theme
Refactors and adds options for the chruby segment. Documentation updated accordingly.
=> Add chruby options

powerlevel9k.zsh-theme, test/segments/rust_version.spec
=> Fixed prompt_rust_version to avoid grep aliases

powerlevel9k.zsh-theme, test/powerlevel9k.spec, test/segments/command_execution_time.spec, test/segments/dir.spec, test/segments/go_version.spec, test/segments/kubecontext.spec
For terminal emulators such as [suckless](https://st.suckless.org/), the most common scenario of icons being cut off is the virtual identifier before the segment content, even though there is a space between the icon and the text. The reason is that we add color only to the icon but not to the space next to it. To fix it, just add color to both the icon and its neighboring space. It allows the terminal emulator to render the icon correctly without introducing any visual side effects.
Here is a screenshot showing the cut-off before (the first line) and after (the second line) applying the patch:
This is superior to existing workarounds mentioned in #231 #453 #794 since we do not need to waste an extra space.
=> Fix icons cut off in some terminal emulators

powerlevel9k.zsh-theme
ZSH displays the right prompt indented one space from the right
margin. This can be tweaked with `ZLE_RPROMPT_INDENT=0`, but that
makes display problems very likely and I don't recommend it. But
all is not lost.
The %E prompt format does continue the current background color
through that last indent space. So it can *look* like our prompt
goes right up to the margin, if:
1) We remove the trailing space from the last segment, and
2) We add %E before clearing the background color
=> Hide one-space indent at right margin

.travis.yml, powerlevel9k.zsh-theme, test/segments/status.spec
This fixes #903 . The problem here was that I made some variables local, but `RETVAL` must be global. In `powerlevel9k_prepare_prompts` (precmd hook) we save the return value of the last executed command. This must be done at the very top of that function, otherwise we get the return value of another command. E.g.:
```
local xxx
RETVAL=$?
```
will always have a RETVAL of 0, because it gets the return value of `local xxx`.
=> FIx status segment

README.md, powerlevel9k.zsh-theme
Fix #839 #879.
* Get the version being used by taking the output of the `pyenv version-name` command.
* Get the global Python version by reading global  `$(pyenv root)/version` file.
* Add variable `POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW` similar to `rbenv`.
=> Fix `pyenv` segment

powerlevel9k.zsh-theme
File `$(pyenv root)/version` may not be created if the `pyenv global` command never be used.
=> Additional fix to `pyenv` segment

powerlevel9k.zsh-theme
Bugfix for issue #907 
The issue is that this strategy requires absolute paths to work, which is usually only available when `POWERLEVEL9K_DIR_PATH_ABSOLUTE` is set to true. This fix works around this limitation by using absolute paths and then changing the path at the end to `~/...` format if required.
This requires the use of a helper function `getUniqueHomeFolder` to determine the unique name of the home folder in order to replace that with `~`.
=> [Bugfix] Fix for "truncate_to_unique" strategy

powerlevel9k.zsh-theme, test/segments/laravel_version.spec
If PHP could not find the artisan file when building the prompt, it would output `Could not open input file: artisan` to stdout. Where only stderr was being redirected to /dev/null, this output would get placed into `laravel_version` variable and displayed on the prompt.
Also the output of `php artisan --version` follows the format `Laravel Framework <version number>`, so I adjusted pulling just the version number out accordingly.
The reference PR and conversation about this error can be found here: https://github.com/bhilburn/powerlevel9k/pull/818
On a side note, this is hands down my favorite zsh theme!
=> [Bugfix] Fix error in laravel_version when artisan is not present

debug/font-issues.zsh
The new GitHub Issue Templates show that a lot of folks have trouble with fonts and problems with the `debug/font-issues.zsh` script. The script is a port of the font detection from [dylanaraps/neofetch](https://github.com/dylanaraps/neofetch). In the our previous version I missed some functions (`get_ppid` and `get_process_name`) that now cause trouble.
Last but not least, I updated the font detections functions.
It would be super helpful if somebody could test this under WSL and Linux.
=> Fix font issue debugging script

functions/colors.zsh
Before function getColorCode consider value 'none' like a bad value and search for another value that could match.
Now function getColorCode consider value 'none' like a good value and no longer seeks to replace it.
When it's use to set background the segment become transparent.
=> [Bugfix] Resolve #918 Transparent background

functions/colors.zsh, powerlevel9k.zsh-theme, test/functions/colors.spec, test/powerlevel9k.spec, test/segments/command_execution_time.spec, test/segments/dir.spec, test/segments/go_version.spec, test/segments/kubecontext.spec, test/segments/laravel_version.spec, test/segments/rust_version.spec, test/segments/status.spec, test/segments/vcs.spec
Added magenta and cyan that were only present with their alternative
names (fuchsia and aqua). See [here](https://en.wikipedia.org/wiki/X11_color_names#Clashes_between_web_and_X11_colors_in_the_CSS_color_scheme).
This fixes #921 
@vaskark could you checkout this PR and see if that helps?
Disclaimer: 
By the help of the wikipedia article, I just found `cyan` and `magenta` to have problems. Please post here, if you found other colors that do not work as intended.
For everyone to test:
You need to set a background color for a segment that is unknown to our internal colors array. If that happens, the segment separator to the next segment shows up in black. This is how you know that this color is unknown.
=> Add missing colors to fix color comparison

functions/icons.zsh
This pull-request is adding the linux icon as a fallback for the fonts without specific linux distro icons.
This is related to #936 and #949
=> Add fallback icon for linux distros

README.md
Fix broken link referencing zsh date and time configuration in prompt expansion. 
The current broken link points to `http://zsh.sourceforge.net/Doc/Release Prompt-Expansion.html`, while the correct link is http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Date-and-time
Thank you so much for opening a PR for P9k! Many of our best features and segments have come from the community, and we are excited to see your contribution.
To help you make the best PR, here are some guidelines:
- The `master` branch is our *stable* branch, and the `next` branch is our development branch. If you are submitting a bug fix, please file your PR against `master`. If it is a new feature, enhancement, segment, or something similar, please submit it against `next`. For more information, please see our …
=> Fix broken link in README referencing date and time configuration

segments/os_icon.p9k
The nerd font icon needs to be updated. Please check the nerd font cheatsheet.
e.g. old arch icon                        'uf300'
current                                 'uf303'
=> [Bugfix]update the icons for nerd font

docker/base-5.0.3/Dockerfile, docker/base-5.5.1/Dockerfile
I used [this](https://launchpad.net/ubuntu/+source/zsh) as a reference to update some package names for Dockerfiles
This relates to @dritter's commit 4f2286265bd18bf37bfd931cefafea1b86917391
=> [Bugfix] updates package name for docker (5.0.2 and 5.5.1)

generator/default.p9k
This PR fixed an error message when you have an empty prompt element array
=> [FIX] Fixed error with empty prompt element array

segments/background_jobs.p9k, test/powerlevel9k.spec, test/segments/background_jobs.spec
This update gets rid of the external calls. In addition, it can now show Running jobs as well as Suspended jobs.
If `POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE` is set, the segment will display if the job count is more than 0.
If `POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS` is set, it will always show the segment, with `⚙ 0` - if there are none. (Note that this will _always_ override `POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE` to be true).
If `POWERLEVEL9K_BACKGROUND_JOBS_EXPANDED` is set, the new format will display
`⚙ 2r 1s` - indicating (r)unning and (s)uspended jobs,
otherwise it will display just the total of the two,
`⚙ 3` - indicating the total.
This PR replaces #935
=> [Enhancement] New Background Jobs segment (070 update)

functions/autoload/__p9k_truncate_path, segments/dir.p9k, test/segments/dir.spec
New strategy for the dir segment - truncate_from_left
This adds the ability to shorten a directory from the left. It leaves just the end of a folder name untouched. E.g. your folders will be truncated like so: "/..9k/..st/segments". How many characters will be untouched is controlled by P9K_SHORTEN_DIR_LENGTH.
NOTE: Created in response to #885
This PR replaces #889
=> [Enhancement] Dir - truncate_from_left (070 update)

segments/dir_writable.p9k
Segments without content (besides a visual identifier) need to overwrite the condition. This condition gets evaluated, hence we need to enclose the condition with `[[` brackets.
=> Fix dir_writable segment

segments/root_indicator.p9k
This fixes #1010 
The root indicator segment did not print anything, because the condition was wrong (it needs to include the `[[` brackets).
Additionally I updated the flash icon to NerdFonts v2.0.
=> Fix root indicator

functions/utilities.zsh, segments/anaconda.p9k
This PR replaces two instances of `$(basename $x)` with `${x:t}`
=> [Fix] Replace calls to basename

functions/utilities.zsh
=> [Fix] Hide __p9k_detect_os grep output on Android

README.md, segments/vcs.p9k, test/segments/vcs_git.spec
Add `POWERLEVEL9K_VCS_GIT_ALWAYS_SHOW_REMOTE_BRANCH='1'` to your zshrc if you would to see remote branch in any cases.
=> [Enhancement] Add option to always show remote branch

docker/base-5.6.2/Dockerfile
```
root@34366f8998aa:/# apt-cache policy zsh
zsh:
Installed: (none)
Candidate: 5.6.2-3
Version table:
5.6.2-3 500
500 http://deb.debian.org/debian buster/main amd64 Packages
```
How about something like this to determine version first?
```
$ apt-cache policy zsh |grep 5.5.1 |head -1 |awk '{print $2}'
5.5.1-1ubuntu2
```
=> Fixes zsh version for Dockerfile for zsh 5.6.2

segments/vcs.p9k, test/segments/vcs_git.spec
This fixes #691 
VCS_INFO has showing the number of steps in a rebase already builtin. Just need to activate and define the format ([documentation](http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#vcs_005finfo-Configuration)):
Caveat:
We can only apply one `actionformat`, thus this information is also printed on other actions (like `merge`), where it is rather useless..
Secondly, this change now prints if there are incoming/outgoing changes when merging/rebasing (See 207874b21cedc0fa54ca11863a4ad660a05b35d0).
I haven't changed the tests yet, so I expect a couple of failures there. Just wanted to discuss the feature first.
//cc @cybercussion
=> Show number of steps to go when rebasing/merging

segments/vcs.p9k, test/segments/vcs_git.spec
This PR gets rid of the slow `git status` part. It makes use of `git ls-files`, which is much faster (thanks to @tupton for the hint in https://github.com/bhilburn/powerlevel9k/issues/60#issuecomment-368130608). Even git submodules are covered by  `git submodule foreach --recursive`.
This PR currently flips `P9K_VCS_SHOW_SUBMODULE_DIRTY`, so that new users won't see changed files in submodules.. Probably this is not necessary any more (my first version used the old `git status`, thus I added an if) and can be flipped back.
=> Speedup vcs: Get rid of git status

segments/battery.p9k, test/segments/battery.spec
I added support for two batteries.
Most of the logic stays the same. It does take into account if the capacities of the batteries are different and should work normally if only one battery is present.
The time remaining or until full charge is taken from the two `acpi` lines. I could only see one "active" at a time. Active being a battery being charged or discharged with a time count. That's why I don't aggregate the time valuesand just pick the one that is not empty.
=> [Enhancement] Adds support for multiple batteries in battery segment (on linux)

functions/vcs.zsh, test/segments/vcs-git.spec
This is a backport from the latest speed improvements from `next` as requested in https://github.com/bhilburn/powerlevel9k/pull/1045#issuecomment-434410608
=> Speedup vcs master

segments/vcs.p9k, test/segments/vcs_git.spec
This PR changes the way how stashes are counted. Previously the stashes were counted via `git stash list | wc -l`, now they are counted without invoking `wc` or even `git`.
Secondly this fixes an issue with the untracked files: That code worked only within the current directory. So if you have untracked files in your repo root and change into a clean subdir, you never saw the untracked icon. This is now fixed.
Talking in speed:
`time ( repeat 10; do; prompt_vcs "left" 1 false > /dev/null; done;)` in my P9K dev repo with 65 stashes:
**1,57s user 1,68s system 85% cpu 3,804 total**
Old segment from `next` (5200a1ba2274e5383f2207caecc5d8b3c0e9c242):
**2,32s user 2,58s system 83% cpu 5,864 total**
@Erowlin could you double check the speed improvements?
=> Speedup VCS Segment 4

segments/battery.p9k, test/segments/battery.spec
This PR aims to replace `acpi` as a dependency for showing remaining charge and discharge time by using data from battery folders in `/sys/class/power_supply`.
I have only limited access to different hardware, so I'd appreciate it if somebody could test this code on different machines. Mocking tests won't help me here. If it should not work, please provide detailed information about the contents of folders in `/sys/class/power_supply`.
P.S.: I only added the code and didn't update the tests yet
=> [Enhancement] Replacing acpi

segments/dir.p9k
The `truncate_with_package_name` shortening strategy now makes use of `__p9k_upsearch`. So now the current directory must not be inside a git checkout any more.
=> Improve truncate_with_package_name strategy

segments/vcs.p9k, test/segments/vcs_git.spec
* Unify two "default values" sections to be consistent with other segments, and resolve double-set `P9K_VCS_SHOW_SUBMODULE_DIRTY` default in favor of the current documentation.
* Fix fatal errors emitted when the CWD is inside a submodule's tree.
* Modify logic so that the `VCS_WORKDIR_HALF_DIRTY` status reflects the untracked file state from the *current repo down* instead of always going back to the highest-level repo.
* Modify flow to skip the check completely if the CWD is the local `.git` folder (it's not considered to be a part of the working tree).
* Optimize the routine a bit by skipping the recursive submodule check if the `VCS_WORKDIR_HALF_DIRTY` status can be established by the presence of untracked files in the current repo's tree.
=> [Bugfix] Fix errors emitted by VCS segment's untracked file check when in a submodule

README.md
All POWERLEVEL variables and directory paths should be formatted with backticks for inline code.  If not marked as code, the ~ home directory can unintentionally apply strikethrough.
=> [Docs] Uniformly apply inline code formatting in README

test/suite.spec
shUnit is capable of outputting ANSI-Colors. By default shUnit detects the coloring capabilities of the terminal automatically. This seems to fail for travis. This PR enforces colored output.
=> Enable colors on Travis

functions/autoload/__p9k_get_unique_path
This ignores `no matches found` error for handling decomposed UTF-8 encoding for non-ASCII character handling in macOS, by applying nullglob when matching directories.
Although this is does not _completely_ resolve the issue, it gracefully fails and simply show the full path for the directory with encoding problem—thus an ad hoc fix. 
Fixes #1067
=> [Bugfix] Ad hoc fix for `no matches found`

powerlevel9k.zsh-theme
Following a prezto update, the flag value of the VIRTUAL_ENV_DISABLE_PROMPT variable is now 12 (https://github.com/sorin-ionescu/prezto/blob/e9387a177e04b05dcf4f82e622615ddd32c558db/modules/python/init.zsh#L103).
=> [Bugfix] Update VIRTUAL_ENV_DISABLE_PROMPT value

test/functions/icons.spec
In `next` the icons are defined in the segment files itself. This PR adds tests for all segments to check that the locale does not get overwritten.
=> Ensure locale is protected in all segments

segments/dir.p9k, test/segments/dir.spec
If the user sets `P9K_DIR_PATH_ABSOLUTE`, the absolute path must be determined before the path is truncated.
// cc @Syphdias
=> Fix truncations with absolute path

segments/battery.p9k, test/segments/battery.spec
This aims to only only show `(...)`instead of the remaining charge/discharge time, if the state of the batteries is unclear, i.e. while the status is `Charging` or `Discharging` but the charge rate, e.g. `power_now`.
If the `power_now` is 0 and the battery status is `Unknown` however. This will be ignored now. This can be the case one or multiple batteries are nearly full (\~98%) but stopped charging. Which seems to be the case quite frequently (examples from @dritter, @JulienPivard and myself)
I also added some test to ensure i behaves correctly.
=> [Bugfix/Enhancment] battery segment: Hides `(...)` if battery status is unknown on Linux

segments/swap.p9k
`sysctl vm.swapusage` returns a single line, `vm.swapusage: total = 1024,00M  used = 379,25M  free = 644,75M  (encrypted)`, so it is easy to parse the result in one RegEx.
=> Improve swap parsing

docker/base-4.3.11/Dockerfile, docker/base-5.0.3/Dockerfile, docker/base-5.1.1/Dockerfile, docker/base-5.2/Dockerfile, docker/base-5.3.1/Dockerfile, docker/base-5.4.2/Dockerfile, docker/base-5.5.1/Dockerfile, docker/base-5.6.2/Dockerfile
The Dockerfiles break regularly because of distros releasing patches for ZSH and it seems to be impossible to install a fuzzy version of ZSH (like 5.6.2-*) with `apt-get`. This PR switches to `apt` that has that ability.
//cc @Syphdias
=> Get rid of absolute versions for Dockerfiles

functions/utilities.zsh
Hi, I have a quick fix for #974; we simply check if a file `/etc/os-release` exists, and grep for the appropriate release id if it does. If it does not the case statement reverts back to the default linux icon. This isn't so nice if you *do* in face have one of the pre-made icons (e.g. centos), but if the files are named inconsistently between different hosts, I don't see a good way of getting around that.
=> [Bugfix] Fix for #974

generator/default.p9k, segments/context/context.p9k, segments/newline/newline.p9k, test/powerlevel9k.spec
The surface functions and `if` cases may be called by a script, which means they should work even with `set -u`set.
=> [Bugfix] allow set -u to be used

README.md, powerlevel9k.zsh-theme, test/segments/nodeenv.spec
`NODEENV_DISABLE_PROMPT` is not meant for us. This is similar to #1128 , where we did a similar thing for virtualenv.
=> Remove checking for NODEENV_DISABLE_PROMPT

powerlevel9k.zsh-theme, test/segments/newline.spec
This fixes the newlines in ZSH 5.7 (#1146 ).
@quintrino @nicolasmeric @panosru Could you confirm this works for you?
=> Fix newlines in ZSH 5.7

powerlevel9k.zsh-theme, test/segments/dir.spec
=> [Bugfix] Only abbreviate $HOME at the beginning of cwd

segments/php_version/php_version.p9k
This is a quick PR to fix #1152 . Thanks to @panosru , who found the problem.
Btw. in #1152 we saw `$'\uE63D'` actually outputting the PHP icon. In my tests that did not work. @panosru it looks like, you have some fallback-font. I changed the PHP icon for `awesome-patched` mode to `PHP`, eventually.
=> Fix PHP icon

functions/vcs.zsh
Hide `warning: could not open directory 'blabla/': Permission denied` if there are files/folders inside a git repo with no user access.
Fixes https://github.com/bhilburn/powerlevel9k/issues/1134
Should there be unittests for that?
=> Hide stderr from git ls-files

segments/background_jobs/background_jobs.p9k
Some simple lint.  It should also cause the occasional variable problem go away.
```
prompt_background_jobs:2: bad math expression: operand expected at end of string
```
=> Lint: prompt_background_jobs bad math expressions

functions/utilities.zsh
Without this fix, `set -u` will cause commands to fail because of the
prompt.
=> fix(p9k::defined): work when -u is set

functions/utilities.zsh, powerlevel9k.zsh-theme, test/segments/ip.spec, test/segments/public_ip.spec, test/segments/vpn_ip.spec
Thank you so much for opening a PR for P9k! Many of our best features and segments have come from the community, and we are excited to see your contribution.
To help you make the best PR, here are some guidelines:
- The `master` branch is our *stable* branch, and the `next` branch is our development branch. If you are submitting a bug fix, please file your PR against `master`. If it is a new feature, enhancement, segment, or something similar, please submit it against `next`. For more information, please see our [Developer's Guide](https://github.com/bhilburn/powerlevel9k/wiki/Developer's-Guide).
- We maintain unit tests for segments and features in the `test` directory. Please add unit tests for anything new you have developed! If you aren't sure how to do this, go ahead and file your PR …
=> Use ip command for VPN segment - fix #1125

segments/dir/dir.p9k
Without this, `current_path` would be `~/foo/bar` whereas `package_path` would be `/home/user/foo/bar` which breaks the substring replacement when calculating the subdirectory relative to the package (making the truncation far too greedy).
I presume there is a reason for the complexity in this:
```zsh
local zero='%([BSUbfksu]|([FB]|){*})'
subdirectory_path=$(__p9k_truncate_path "${current_path:${#${(S%%)package_path//$~zero/}}}" $P9K_DIR_SHORTEN_LENGTH $P9K_DIR_SHORTEN_DELIMITER)
```
And that something simpler would not work? Something like this
```zsh
subdirectory_path=$(__p9k_truncate_path "${current_path/${package_path}/}" $P9K_DIR_SHORTEN_LENGTH $P9K_DIR_SHORTEN_DELIMITER)
```
=> [Bugfix] dir: Fix package name path truncation inside home dir

powerlevel9k.zsh-theme
This is a Backport from @wrboyce 's fix for truncating dir with package name from #1158
=> Fix home dir shortening when using package_name truncation strategy

README.md
The option was not mentioned in the README.
Code was added in #830.
=>  [Docs] Added doc for POWERLEVEL9K_BATTERY_HIDE_ABOVE_THRESHOLD

.gitignore
I have a zshexit hook that zcompiles every `*.p9k` file and some other zsh stuff.
To keep my git status clean I would like ignore `*.zwc` files.
=> adds *.zwc to .gitignore

generator/default.p9k
When generating a right-side prompt segment that has an icon but no other content (like `status` in the `OK` state), whitespace is inserted both before and after this empty content, resulting in an extended prompt segment. When there is content, it looks fine, because there should be whitespace on both sides of the text:
(Showing `status` segment on both left and right for comparison.)
This fix modifies the logic in `default.p9k` for right-side prompt generation so that a second whitespace character is not inserted in the event of an empty `${content}` string. However, it leaves the previous bracketing whitespace intact if content exists:
=> [Bugfix] Right-side prompt segments with an icon but no content double-print whitespace

segments/command_execution_time/command_execution_time.p9k, segments/command_execution_time/command_execution_time.spec
I wanted to add an "s" after the seconds display, in the case that the execution time was under a minute, to make it clearer what units were being displayed, when there were no colons. 
In the process of investigating this modification, I noticed that the code for formatting either whole or partial seconds (depending on the `P9K_COMMAND_EXECUTION_TIME_PRECISION` variable) seemed unnecessarily complex. By eliminating the pre-declaration of the number type and replacing it with a `printf` statement to format on the fly, I was able to squash a three-way `if`/`elif`/`else` control structure into a single line.
I also noticed that all this formatting was being done every time, regardless of whether the execution time actually exceeded the threshold, so I moved that logic to the front of the …
=> [Enhancement] Refactor command_execution_time.p9k segment

functions/utilities.zsh, powerlevel9k.zsh-theme
This pull request resolves the `prompt_vcs:6: command not found: vcs_info` error that occurs when using the `vcs_joined` segment in place of the `vcs` segment. Fixes #1116.
=> [Bugfix] Ensure that vcs init is invoked when using the "vcs_joined" segment. 

segments/vcs/vcs_git.spec
Currently running the git unit tests unsets name and email in the global git config.
This PR gets rid of unnecessary variable juggling and simply sets the git config in the new home. The config (`/tmp/powerlevel9k-test/.gitconfig`) will be removed when the test directory is removed. I also added a "test" (which is a bit of a hack) to check if email or name were changed.
PS: Teardowns are currently called an additional time (see https://github.com/kward/shunit2/issues/112 for details) after shunit finished all tests. It should be fine for now. Just a heads up since I stumbled upon this bug while testing.
=> [Bugfix] Don't unset global git user config after git tests

segments/vcs/README.md, segments/vcs/vcs.p9k
This adds a new hook `vcs-icon`, that sets the icon based on the VCS used and the remote URL.
Fixes #1207
=> Fix remote icon detection

README.md
I noticed that the environment variable POWERLEVEL9K_RBENV_ALWAYS doesn't seem to do anything or to be referenced anywhere in the source outside of README.md. Seems like it might have been an anachronism left hanging when the variable was renamed to POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW?
=> [Docs] remove reference to POWERLEVEL9K_RBENV_ALWAYS

segments/status/README.md
This correctly some documentation for the `status` segment and adds some examples.
=> [Docs] updates `status` README

functions/icons.zsh
`show_defined_icons` prints out all defined icons. Before, it just printed the internal name, which was not very helpful to users. Now it prints the copy&paste ready variable name plus a info on how to use these variable overrides.
=> Improve show_defined_icons

segments/background_jobs/background_jobs.p9k
The `background_jobs` segment now reports the jobs count immediately. We trap `CLD` (Child process was killed) here, taken from [here](https://www.zsh.org/mla/users/2001/msg00719.html).
Caveat: It might cause some trouble, if in multiline-prompts (cursor position changes, when we show the segment).
Performancewise, this redraws the complete prompt on every child exit (solvable in #1176 ).
I haven't tested it much (running out of time again), and I am not a fan of trapping signals all over, but that seems to be our only chance..
// cc @Syphdias 
Fixes #1196 .
Succeeds #1238 .
=> Fix background jobs segment

segments/battery/battery.p9k, segments/battery/battery.spec
This merely removes the extra checking for `P9K_BATTERY_LEVEL_BACKGROUND` AND `P9K_BATTERY_STAGES` being set at the same time. ([here](https://github.com/bhilburn/powerlevel9k/compare/next...Syphdias:batter-stages#diff-972d8453b66adcec8415788a9f7aa1d7L209))
The variables are checked independently anyway since the features are independent.
Fixes #1245
=> [Bugfix] Makes `P9K_BATTERY_LEVEL_BACKGROUND` and `P9K_BATTERY_STAGES` usable separately

segments/status/status.p9k
I pull this plugin from the `next` branch (for the new features it provides). Recently I've noticed that my local machine shows the following error on startup:
```
prompt_status:16: bad math expression: operand expected at end of string
```
Looking into it, it seems like both the `ec` and the `ec_sum` variable are not being initialised. This results in an incorrect arithmetic expression of `$(( + ))` being evaluated.
The actual solution for this might be to actually fix the underlying cause but I though this PR would be appropriate to start a discussion about where the issue might be and why it is showing up for me specifically.
=> Fix prompt status error

.travis.yml
Seems like the default image has changed. Here the package name
has changed from `node` to `nodejs`.
=> Fix tests on travis

segments/rbenv/rbenv.p9k
Similar to #1283
resolves #1282
=> [Bugfix] rbenv doesn't respect POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=false

segments/virtualenv/virtualenv.p9k
=> [Bugfix] Removes whitespace from virtualenv icon if Awesome-Mapped-FontConfig is uses (for consistency)

segments/pyenv/pyenv.p9k, segments/rbenv/rbenv.p9k
I removed some of the complexity and manual checking for versions. `pyenv` and `rbenv` should:tm: take care of that themselves. This seems to me like the most straight forward solution to not introducing unexpected behaviour. This would also close 3 issues (and 2 PRs I opened without simplifying code).
I did only very little testing since I know very little about `pyenv` and `rbenv` and these segments have no unit test.
=> [Bugfix] Simplifing pyenv and rbenv to get rid of unexpected behaviour

generator/default.p9k, segments/newline/newline.spec
This fixed a bug where the last line is not properly rendered if there is a hidden segment at the end:  
`P9K_LEFT_PROMPT_ELEMENTS=(dir newline background_jobs newline dir_writable)`
This PR initially was created to fix #1266. What this does not change is the displaying of the "triangle" (`LEFT_SEGMENT_SEPARATOR`) at the end on newline. Currently the triangle is not shown if there is no segment on this line. This [could be considered a bug](https://github.com/bhilburn/powerlevel9k/issues/1266#issuecomment-493737977) as @romkatv notes, depending on if want that or not. So the question is: Should the triangle be displayed on empty lines? If no, this PR is finished (unless the review brings something up), if so, I could expand on this PR.
=> [Bugfix] fixes hidden segment on last line

segments/vpn_ip/vpn_ip.p9k
This is a small change to also register interfaces that are not just `tun` but also every interface that starts with "tun".
I do have another problem though:
My non-active VPN interface (`tap0`) is `UP` and my actually working VPN (`tun0`) ins `UNKNOWN`.
`p9k::parseIp` currently needs the interface to be `UP`. This breaks the segment for me atm.
```zsh
❯ /sbin/ip -brief -4 a show
lo               UNKNOWN        127.0.0.1/8 
wlp42s0          UP             10.4.5.6/24 
tap0             UP             10.3.4.5/24 
docker0          DOWN           10.2.3.4/27 
tun0             UNKNOWN        10.1.2.3/32 
```
=> [Enhancement & Bug?] Better P9K_VPN_IP_INTERFACE default

functions/colors.zsh, test/functions/colors.spec
This enables users to use truecolor/24bit colors if zsh (>=5.7) and the terminal support it.
To display similar colors if the terminal does not support truecolor, we should document somewhere to recommend the following lines to add to the `.zshrc`:
```zsh
[[ $COLORTERM = *(24bit|truecolor)* ]] || zmodload zsh/nearcolor
```
After this change the following colors formats are supported (this should also be documented):
```zsh
P9K_DIR_PATH_HIGHLIGHT_FOREGROUND='001'     # numeric 001-256 (1-16 are dynamically used for themes for example)
P9K_DIR_PATH_HIGHLIGHT_FOREGROUND='#d10000' # hex code #000000-#ffffff
P9K_DIR_PATH_HIGHLIGHT_FOREGROUND='red'     # name, see `p9k::get_color foreground`
```
I write "should" because the [Customization …
=> [Enhancement] adds support for truecolor/24bit

functions/icons.zsh, generator/default.p9k, test/core/bold.spec
Instead of `_BACKGROUND`, `_FOREGROUND` or `_ICON` you can append:
- `_BOLD` to the stateful name to get bold text
- `_ICON_BOLD` to the stateful name to get bold visual identifier/"icon"
(this only works if the font allows for it to be bold)
The `_BOLD` feature seems to be undocumented which should be changed. And
also document `_ICON_BOLD` next to it.
aims to resolves #1223
=> [Enhancement] Bold Icons

functions/utilities.zsh
Fix failed attempt to open nonexistent `/proc/1/stat`.
Previously, when a terminal is not found, it climbs up the proccess tree
until it tries to open `/proc/1/stat` and fails with
`__p9k_detect_terminal:23: no such file or directory: /proc/1/stat`.
This appears to be harmless, but gives an annoying error whenever
starting zsh.
Sliding the pid check before the
`proc_stat=(${(@f)$(</proc/${pid}/stat)})` solved this problem.
Also adds `xfce4-terminal` to list of terminal emulators.
Signed-off-by: Hal Gentz <zegentzy@protonmail.com>
Btw, I'm liking this new `next` branch. The time between prompts showing up has gone from a sluggish ~0.5s to a wonderful ~0.05s. Thank you!
=> [Bugfix] Fix failed attempt to open nonexistent `/proc/1/stat`.
